### ISSUE TITLE
Thanks for the improved group reports!

### ISSUE THREAD

**Issue by dkp** [nipreps/mriqc#1003]
MRIqc is such an important tool.  I'm delighted to see the update and improvements.  WRT the legends, I'm assuming Ctx GM=cortical GM, dGM is deep GM, what is Crown??

Thanks so much

**Comment by psadil** [comment]
@dkp, I'm not a developer but was wondering the same. For future reference, the crown appears to refer to a shell around the brain mask with thickness of 2 voxels. See https://osf.io/hz52v/ and https://www.liebertpub.com/doi/full/10.1089/brain.2014.0321

**Comment by effigies** [comment]
Yes, that's correct.

**Comment by dkp** [comment]
Thanks so much! Very helpful.
