### ISSUE TITLE
FIX : MRIQC docker provenance in documentation

### ISSUE THREAD

**Issue by celprov** [nipreps/mriqc#1011]
[The MRIQC documentation](https://mriqc.readthedocs.io/en/stable/docker.html) should point to the latest version of the `docs/source/docker.rst`, because in the current version the MRIQC docker is still listed under poldracklab.

**Comment by oesteban** [comment]
I believe this is the confluence of two circumstances/issues:
- You are looking at the "stable" version of the documentation (see updated https://mriqc.readthedocs.io/en/latest/docker.html)
- ReadTheDocs was failing to build new versions of the documentation up until a few minutes ago.

I'm closing this issue, and the stable version of the docs should be updated when the next time we cut a new release.
