### ISSUE TITLE
allow setting .cache location via environment variable

### ISSUE THREAD

**Issue by bloyl** [nipreps/mriqc#1029]
On some HPCs mriqc fails because `/home/bidsapp` is located on a readonly filesystem (see https://neurostars.org/t/mriqc-v0-15-2-read-only-error-on-hpc-cluster-oserror-errno-30-read-only-file-system-home-bidsapp-cache-mriqc/7005).

While the solution mentioned in the above works it requires the user to have control over the singularity call, which isn't always possible, for instance in flywheel or XNAT gears/modules.

It would be convenient if mriqc used an environment variable similar to (https://numba.readthedocs.io/en/stable/reference/envvars.html?highlight=ENVIRONMENT#envvar-NUMBA_CACHE_DIR) to allow user control over where this written.

Best,

**Comment by oesteban** [comment]
This is a great idea! Would you like to contribute it?
