### ISSUE TITLE
consistant result of "Detected a zero-filled frame, has the original image been rotated?"

### ISSUE THREAD

**Issue by zhaolu660** [nipreps/mriqc#1035]
Hi,

I am a new user of the MRIQC tool. For testing, I have run MRIQC on 20 sMRI scans through docker. It is striking I got constant result "Detected a zero-filled frame, has the original image been rotated?", no matter how the real image quality is. Here I attached screenshots of the reports for cases of "good","motion" and "corrupted reconstruction". 

I used the standard commond: 
docker run -it --rm -v <input dir>:/data:ro -v  <output dir>:/out nipreps/mriqc:latest /data /out participant --participant_label  <subjID> --no-sub --verbose-reports

It looks, for me, the trained model did not work for my independent dataset. Is there any suggestion to address such issue?

Thank you very much!

Lu

![Screen Shot 2022-10-11 at 1 34 45 PM](https://user-images.githubusercontent.com/20667004/195464801-ba73e19a-67a0-486d-98c1-8842db59c5bf.jpg)
![Screen Shot 2022-10-11 at 1 35 08 PM](https://user-images.githubusercontent.com/20667004/195464799-daaf487e-bd43-46f9-be1b-30820b539a56.jpg)
![Screen Shot 2022-10-11 at 1 35 22 PM](https://user-images.githubusercontent.com/20667004/195464795-9488bd48-49a3-4890-b32d-1b0a56f46df3.jpg)

**Comment by trevorbryanjackson** [comment]
I'm having a similar issue with my dataset. RAW T1w, fresh from DICOM conversion.

**Comment by oesteban** [comment]
The heuristic was producing too many false positives. It has been disabled as of 23.1.0.
