### ISSUE TITLE
Which software has been used for the html report generation

### ISSUE THREAD

**Issue by AaronReer** [nipreps/mriqc#1037]
Hi,

We are currently developing a software for the QC of MEG data. This should be similar to mriqc with respect to usability (BIDS app) and the output generated by the tool. For the latter I was wondering which software you use to generate the html reports or if you have created the html strings yourself (and if so which was the software used for the plots of your metrics). 
I would appreciate your help!
Thanks in advance,

Aaron

**Comment by oesteban** [comment]
Hi @AaronReer, apologies for the slow response.

We are actually slowly outsourcing MRIQC's visualization tooling to [nipreps/nireports](https://github.com/nipreps/nireports) to help with this particular use case.

That said, the NiPreps community would have open arms to some MEGQC application, if you want to develop it following the community guidelines (see section on the community and contributions at https://nipreps.org)
