### ISSUE TITLE
"File name too long" error

### ISSUE THREAD

**Issue by jbwexler** [nipreps/mriqc#1038]
I'm using v22.0.6. I posted the same issue here: https://github.com/poldracklab/tacc-openneuro/issues/44

> Node: mriqc_wf.funcMRIQC.ComputeIQMs.metadata
> Working directory: /scratch1/03201/jbwexler/work_dir/mriqc/ds003430_sub-04/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003430-mriqc..sourcedata..raw..sub-04..ses-perceptionNaturalImageTraining01..func..sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz/metadata
> 
> Node inputs:
> 
> bids_dir = None
> bids_validate = True
> in_file = /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds003430-mriqc/sourcedata/raw/sub-04/ses-perceptionNaturalImageTraining01/func/sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 576, in _send_procs_to_workers
>     self.procs[jobid].run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 515, in run
>     os.makedirs(outdir, exist_ok=True)
>   File "/opt/conda/lib/python3.9/os.py", line 215, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/opt/conda/lib/python3.9/os.py", line 225, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 36] File name too long: '/scratch1/03201/jbwexler/work_dir/mriqc/ds003430_sub-04/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003430-mriqc..sourcedata..raw..sub-04..ses-perceptionNaturalImageTraining01..func..sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz'
> 
> 
> During the creation of this crashfile triggered by the above exception,
> another exception occurred:
> 
> [Errno 36] File name too long: '/scratch1/03201/jbwexler/work_dir/mriqc/ds003430_sub-04/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003430-mriqc..sourcedata..raw..sub-04..ses-perceptionNaturalImageTraining01..func..sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz/metadata/result_metadata.pklz'.
> ...skipping...
> Node: mriqc_wf.funcMRIQC.ComputeIQMs.metadata
> Working directory: /scratch1/03201/jbwexler/work_dir/mriqc/ds003430_sub-04/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003430-mriqc..sourcedata..raw..sub-04..ses-perceptionNaturalImageTraining01..func..sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz/metadata
> 
> Node inputs:
> 
> bids_dir = None
> bids_validate = True
> in_file = /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds003430-mriqc/sourcedata/raw/sub-04/ses-perceptionNaturalImageTraining01/func/sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 576, in _send_procs_to_workers
>     self.procs[jobid].run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 515, in run
>     os.makedirs(outdir, exist_ok=True)
>   File "/opt/conda/lib/python3.9/os.py", line 215, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/opt/conda/lib/python3.9/os.py", line 225, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 36] File name too long: '/scratch1/03201/jbwexler/work_dir/mriqc/ds003430_sub-04/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003430-mriqc..sourcedata..raw..sub-04..ses-perceptionNaturalImageTraining01..func..sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz'
> 
> 
> During the creation of this crashfile triggered by the above exception,
> another exception occurred:
> 
> [Errno 36] File name too long: '/scratch1/03201/jbwexler/work_dir/mriqc/ds003430_sub-04/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003430-mriqc..sourcedata..raw..sub-04..ses-perceptionNaturalImageTraining01..func..sub-04_ses-perceptionNaturalImageTraining01_task-perceptionNaturalImageTraining_run-01_bold.nii.gz/metadata/result_metadata.pklz'.

**Comment by oesteban** [comment]
Hi @jbwexler, a way to go around this is setting ``parameterize_dirs = false`` in the [nipype config file](https://nipype.readthedocs.io/en/1.1.0/users/config_file.html).

Since you are running on singularity, I guess your home directory will be bound in the container and therefore writing the config in `$HOME/.nipype/nipype.cfg` should do.

cc/ @effigies
