### ISSUE TITLE
Documentation of updated carpetplots

### ISSUE THREAD

**Issue by SRSteinkamp** [nipreps/mriqc#1039]
Dear all,

thank you for providing such a great tool. I think, however, that the documentation should be updated:

The documentation for the newer versions of MRIQC still uses the older carpetplot and neither explains the legend nor reference the meaning of the separations. Only after an extended search, I was able to find an answer in #1003. 

Best
Simon

**Comment by celprov** [comment]
Dear Simon,
Thank you for reporting this important issue! The documentation will be been updated with the new carpetplot image and its description once the pull request #1045 will be merged.
