### ISSUE TITLE
0.16.0 docs are not on rtd

### ISSUE THREAD

**Issue by asmacdo** [nipreps/mriqc#1054]
Looks like all the other versions are there though.

![2023-02-07-090422_296x363_scrot](https://user-images.githubusercontent.com/1028657/217266813-296755c7-5b57-4f48-bdb7-42d6d100a826.png)

**Comment by oesteban** [comment]
Thanks for letting us know. I've quickly checked and it seems it's trying to install xvfbwrapper when it breaks.

Considering that MRIQC's documentation hasn't changed much, and that we do not actively maintain older versions of MRIQC (unless someone is looking into stability of IQMs, it doesn't make a lot of sense in general), I'm inclined toward deactivating documentation for versions older than 2yo., which should also stimulate people to update to the latest release.

In any case, if anyone wants to dig this up, please reopen the issue.

**Comment by oesteban** [comment]
> could one of you add me?

done!
