### ISSUE TITLE
Why MRIQC is performed using HCP data Resting state data is not performed？

### ISSUE THREAD

**Issue by githubcooperation** [nipreps/mriqc#1055]
After converting the HCP data format to BIDS format, I can run MRIQC for all other data and get the corresponding results, but I can't get the results for resting data only. And no error is reported. What is the problem? I am using the singularity version of MRIQC. Thank you for answering my question!

**Comment by oesteban** [comment]
Unfortunately, we cannot provide any support with the little information provided in this report. Please open a new issue using this link: https://github.com/nipreps/mriqc/issues/new?assignees=&labels=bug&template=bug_report.yml
