### ISSUE TITLE
Revising maintainers team

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#1065]
### What would you like to see added in this software?

I want to ask @eilidhmacnicol and @esavary to become MAINTAINERS - is that okay with you?

Also, @effigies, do you want to remain a MAINTAINER now that other people are taking in maintenance? (egoistically, I would prefer to keep you as you always have an additive view of things, e.g., https://github.com/nipreps/mriqc/issues/1062#issuecomment-1444865373)

### Do you have any interest in helping implement the feature?

Yes

**Comment by effigies** [comment]
I'm fine staying a maintainer in that people in distress can call on me. I can't commit to additional time for mriqc.

**Comment by oesteban** [comment]
Sounds great! Thanks!

**Comment by oesteban** [comment]
@eilidhmacnicol and @esavary - Would you like to become maintainers of MRIQC?

@eilidhmacnicol - if you can't commit resources directly, would you like to be an "Advisory Member" to assist with generalizations of MRIQC over non-human species?

I've been thinking through this, and maybe @ZviBaratz would like to become a maintainer too, WDYT?

**Comment by esavary** [comment]
Hi! I would be happy to become a maintainer.

**Comment by ZviBaratz** [comment]
@oesteban I'd be happy to help if I can. My availability is somewhat unstable at the moment, but I can definitely try to make time when possible. Perhaps we can schedule a meeting some time to catch up on the current state of things and prioritize goals or sketch a rough roadmap?
