### ISSUE TITLE
Imperfect brain mask with 3dAutomask 

### ISSUE THREAD

**Issue by julfou81** [nipreps/mriqc#1079]
### What happened?

Using MRIQC v22.0.6, I noticed that for some subjects the brain mask calculated for functional images is imprecise, taking too much outside brain tissues. 
For the same subjects, using for instance MRIQC v0.14.2, the brainmask is much better.

The difference rise from the use of different skullstrip programs for brain extraction: FSL-`bet` for v0.14.2 and AFNI-`3dAutomask` for v22.0.6.

Here is an illustration of the difference:

-brain mask for 22.0.6 (with `3dAutomask`):
<img width="1480" alt="Capture d’écran 2023-03-10 à 14 35 20" src="https://user-images.githubusercontent.com/32452352/224331097-fbdf5325-52dc-4f45-a578-69b17559991d.png">

- brain mask for 0.14.2 (with `bet`)
<img width="1479" alt="Capture d’écran 2023-03-10 à 14 35 48" src="https://user-images.githubusercontent.com/32452352/224331342-374ed6de-3333-4cfc-b74e-143211b85b18.png">

This has an impact on the way the outliers are calculated (red curve):
-outliers for 22.0.6:
<img width="1453" alt="Capture d’écran 2023-03-10 à 14 45 05" src="https://user-images.githubusercontent.com/32452352/224331815-72566687-0963-4003-8450-d158dab33b07.png">

-outliers for 0.14.2:
<img width="1377" alt="Capture d’écran 2023-03-10 à 14 44 48" src="https://user-images.githubusercontent.com/32452352/224331907-c1a86514-bd8b-4ae1-9516-10edde9f5cdb.png">

### What command did you use?

```shell
singularity run --cleanenv -B /scratch/jsein/BIDS:/work \
 /scratch/jsein/my_images/mriqc-22.0.6.simg /work/$study  \
 /work/$study/derivatives/mriqc participant group --participant_label $subjs  --n_procs 12    \
   -w /work/temp_data_${study}  --fd_thres 0.5  --verbose-reports  --ica
```

### What version of fMRIPrep are you running?

MRIQC v 22.0.6

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

Brain extraction command for 22.0.6:
```
3dAutomask -apply_prefix sub-1054011_task-rest_bold_valid_volreg_tstat_masked.nii.gz -prefix sub-1054011_task-rest_bold_valid_volreg_tstat_mask.nii.gz /work/temp_data_NEMO/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..work..NEMO..sub-1054011..func..sub-1054011_task-rest_bold.nii.gz/afni_msk/sub-1054011_task-rest_bold_valid_volreg_tstat.nii.gz
```

Brain extraction command for 0.14.2:
```
bet /work/temp_data14p2_NEMO/workflow_enumerator/funcMRIQC/_in_file_..work..NEMO..sub-1054011..func..sub-1054011_task-rest_bold.nii.gz/mean/sub-1054011_task-rest_bold_valid_volreg_tstat.nii.gz /work/temp_data14p2_NEMO/workflow_enumerator/funcMRIQC/fMRIBrainMask/_in_file_..work..NEMO..sub-1054011..func..sub-1054011_task-rest_bold.nii.gz/bet_msk/sub-1054011_task-rest_bold_valid_volreg_tstat_brain.nii.gz -F -m
```

**Comment by oesteban** [comment]
Closing in favor of #1028 because we cannot go back to BET (see #823, #1032)
