### ISSUE TITLE
Version 23.0.0 - can't find subjects in BIDS folder

### ISSUE THREAD

**Issue by vogelbac** [nipreps/mriqc#1086]
### What happened?

I run Docker on a Windows OS and used the Version with the latest tag (23.0.0) I mapped the correct folder and also tested it using  this command to see if the folder is correct listed "--entrypoint /bin/bash nipreps/mriqc:latest"   &  "ls /data". All the subject folders were listed correctly with the sub-XXX id. 

Error was:
mriqc: error: ore or more participant labels wer not found in the BIDS directory: 101

### What command did you use?

```shell
docker run -it --rm -v C:\project\nifti:/data:ro -v C:\project\derivatives:/out nipreps/mriqc:latest /data /out participant --participant_label sub-101
```

### What version of fMRIPrep are you running?

23.0.0

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by cni-md** [comment]
I have the same issue using singularity, but only on subjects with session label. sub-foo/func/ is working. sub-foo/ses-1234/ not.

**Comment by liukang18** [comment]
Confirming that I am also seeing the same behavior as @cni-md. Paths without session folder/id are running fine; Paths with session folder/id are failing. Using the latest (23.0.0) version in docker.

**Comment by effigies** [comment]
Also seeing this in https://github.com/poldracklab/tacc-openneuro/issues/59.

**Comment by oesteban** [comment]
Question to @effigies -- we are currently indexing metadata on the first pass. Is there a way of creating the ``BIDSLayout`` without indexing the metadata, and then at a latter time ask it to index the metadata associated to specific files?

**Comment by effigies** [comment]
I don't think so.

**Comment by oesteban** [comment]
Okay, 23.0.1 has just been posted and should address this issue. Please reopen if it persists.

**Comment by aarthi-ganapathy** [comment]
Hi, I tried using MRIQC Version 23.0.1 after bare metal installation with python, and it is still giving me the following error:

C:\Users\user>mriqc C:/bids C:/MRIQC participant

usage: mriqc [-h] [--version] [-v] [--species {human,rat}]
             [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]] [--session-id [SESSION_ID ...]]
             [--run-id [RUN_ID ...]] [--task-id [TASK_ID ...]] [-m [MODALITIES ...]] [--dsname DSNAME]
             [--bids-database-dir PATH] [--nprocs NPROCS] [--omp-nthreads OMP_NTHREADS] [--mem MEMORY_GB] [--testing]
             [-f] [--pdb] [-w WORK_DIR] [--verbose-reports] [--write-graph] [--dry-run] [--resource-monitor]
             [--use-plugin USE_PLUGIN] [--no-sub] [--email EMAIL] [--webapi-url WEBAPI_URL]
             [--webapi-port WEBAPI_PORT] [--upload-strict] [--notrack] [--ants-float] [--ants-settings ANTS_SETTINGS]
             [--fft-spikes-detector] [--fd_thres FD_THRES] [--deoblique] [--despike] [--start-idx START_IDX]
             [--stop-idx STOP_IDX]
             bids_dir output_dir {participant,group} [{participant,group} ...]
mriqc: error: Querying BIDS dataset at <C:\bids> got an empty result.
Please, check out your currently set filters:

 *participant_label: []
 *session: None
 *run: None
 *task: None
 *bids_type: None

Please help me out with this, thank you!

**Comment by GHarmata** [comment]
I think I may be having the same issue with mriqc version 24.0.2.  I also have the session label for all participants, so it still may be looking for files in the wrong directory level.  Help would be appreciated!


```
 ----------------------------------------------------------------

  * BIDS dataset path: /Shared/data/data_soft_links.
  * Output folder: /Shared/data/derivatives/mriqc/T1w.
  * Analysis levels: ['participant'].
  * BIDS filters-file: /Shared/data/scripts/mriqc/bids_filter_file.json.
------------------------------------------------------------------

usage: mriqc [-h] [--version] [-v] [--species {human,rat}]
             [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
             [--bids-filter-file PATH] [--session-id [SESSION_ID ...]]
             [--run-id [RUN_ID ...]] [--task-id [TASK_ID ...]]
             [-m [{T1w,T2w,bold,dwi} ...]] [--dsname DSNAME]
             [--bids-database-dir PATH] [--bids-database-wipe]
             [--no-datalad-get] [--nprocs NPROCS]
             [--omp-nthreads OMP_NTHREADS] [--mem MEMORY_GB] [--testing] [-f]
             [--pdb] [-w WORK_DIR] [--verbose-reports] [--reports-only]
             [--write-graph] [--dry-run] [--resource-monitor]
             [--use-plugin USE_PLUGIN] [--crashfile-format {txt,pklz}]
             [--no-sub] [--email EMAIL] [--webapi-url WEBAPI_URL]
             [--webapi-port WEBAPI_PORT] [--upload-strict] [--notrack]
             [--ants-float] [--ants-settings ANTS_SETTINGS]
             [--min-dwi-length MIN_LEN_DWI] [--min-bold-length MIN_LEN_BOLD]
             [--fft-spikes-detector] [--fd_thres FD_THRES] [--deoblique]
             [--despike] [--start-idx START_IDX] [--stop-idx STOP_IDX]
             bids_dir output_dir {participant,group} [{participant,group} ...]
mriqc: error: Querying BIDS dataset at </Shared/data/data_soft_links> got an empty result.
Please, check out your currently set filters (with '--bids-filter-file /Shared/data/scripts/mriqc/bids_filter_file.json'):
{'t1w': {'datatype': 'anat', 'suffix': 'T1w'}}
```



The basic file structure of my dataset is as follows (showing the T1w files for a generic subject):

```
data/
    sub-XXXXX/
        ses-XXXXX/
             anat/
                 sub-XXXXX_ses-XXXXX_T1w.nii.gz
                 sub-XXXXX_ses-XXXXX_T1w.json
```

*Note that I have used symlinks to take a non-BIDS-compliant dataset to make it BIDS-compliant.
