### ISSUE TITLE
Skip BOLD files with too few volumes

### ISSUE THREAD

**Issue by effigies** [nipreps/mriqc#1090]
### What would you like to see added in this software?

Runs with 4 or fewer time points will raise an error at the `motion_correct` node. This should be detected at workflow creation time and skipped.

xref https://github.com/poldracklab/tacc-openneuro/issues/58

### Do you have any interest in helping implement the feature?

Yes

**Comment by DominikaZ** [comment]
Hello, is there any update on this? We have some runs that are failing on `< 5 time points per voxel` and would love if the whole mriqc run didn't fail because of them.

**Comment by oesteban** [comment]
Resolved with #1120 in https://github.com/nipreps/mriqc/commit/f39c4bf7bb51bdfc19f9f4872f1da28385ff6254
