### ISSUE TITLE
Issue template asks for fmriprep (not mriqc) version

### ISSUE THREAD

**Issue by yarikoptic** [nipreps/mriqc#1093]
How are those templates also configured since I don't see them in https://github.com/nipreps/mriqc/tree/master/.github  ?

![image](https://user-images.githubusercontent.com/39889/227536618-927b53ac-5ad5-4a48-b24f-ecb2a4166301.png)

**Comment by effigies** [comment]
https://github.com/nipreps/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml

I can't quickly find a way to parameterize these templates to use the current repository name. We can just replace "fMRIPrep" with "the software".

**Comment by oesteban** [comment]
I think I meant to do that. But I might have edited the wrong repository once again.
