### ISSUE TITLE
OSError: No command "mri_robust_template" found with MRIQC v 23.1.0

### ISSUE THREAD

**Issue by julfou81** [nipreps/mriqc#1125]
### What happened?

I have tried the new version (23.0.1) of MRIQC but I encountered the following error:

```
OSError: No command "mri_robust_template" found on host skylake103.cluster. Please check that the corresponding package is installed.
```

### What command did you use?

```shell
singularity run --cleanenv -B /scratch/jsein/BIDS:/work \
 /scratch/jsein/my_images/mriqc-23.1.0.simg /work/$study  \
 /work/$study/derivatives/mriqc23p1 participant group --participant_label $subjs  --n_procs 12    \
   -w /work/temp_data23p1_${study}  --fd_thres 0.5  --verbose-reports
```

### What version of the software are you running?

23.0.1

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
230614-17:21:04,693 cli IMPORTANT:
	 
    Running MRIQC version 23.1.0:
      * BIDS dataset path: /work/NEMO.
      * Output folder: /work/NEMO/derivatives/mriqc23.
      * Analysis levels: ['participant', 'group'].

230614-17:21:15,968 cli WARNING:
	 IMPORTANT: Anonymized quality metrics (IQMs) will be submitted to MRIQC's metrics repository. Submission of IQMs can be disabled using the ``--no-sub`` argument. Please visit https://mriqc.readthedocs.io/en/latest/dsa.html to revise MRIQC's Data Sharing Agreement.
230614-17:22:22,436 nipype.workflow WARNING:
	 Storing result file without outputs
230614-17:22:22,438 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.dwiMRIQC.dwi_reference_wf.epi_merge" (/work/temp_data23p1_NEMO/mriqc_wf/dwiMRIQC/dwi_reference_wf/_in_file_..work..NEMO..sub-pilote1..dwi..sub-pilote1_dir-AP_dwi.nii.gz/epi_merge)
230614-17:22:24,269 nipype.workflow ERROR:
	 Node epi_merge.a0 failed to run on host skylake103.cluster.
230614-17:22:24,270 nipype.workflow ERROR:
	 Saving crash info to /work/NEMO/derivatives/mriqc23/logs/crash-20230614-172224-jsein-epi_merge.a0-da3ec52e-c696-4c3f-895a-9740bf13016c.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node epi_merge.

Cmdline:
	echo Only one time point!
Stdout:

Stderr:

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 752, in _run_interface
	    raise IOError(
	OSError: No command "mri_robust_template" found on host skylake103.cluster. Please check that the corresponding package is installed.
```

### Additional information / screenshots

MRIQC v23.0.0 worked well on this dataset. It seems here that it is the dwi workflow that fails. The `dwi` folder contains two dwi series, with the same b values, one acquired with phase encoding direction in A>P and the other in P>A, with 3 shells (b=300, b=1000 and b2000) with 7 additional b0.

**Comment by araikes** [comment]
I second this error.

**Comment by julfou81** [comment]
I ran the same command on T1w, T2w and bold images only (with the `-m T1w T2w bold` argument) and everything went find. It seems that the bug only affects the dwi workflow.

**Comment by LuRoe7** [comment]
I experience exactly the same error using singularity!

**Comment by araikes** [comment]
@oesteban just a bump on this.

**Comment by tpatpa** [comment]
Same error for me (with diffusion data)..

**Comment by amrshadid** [comment]
same error also for me. any solutions ?

**Comment by effigies** [comment]
It looks like MRIQC doesn't bundle most of freesurfer in its image. A PR to add FreeSurfer would be helpful. The fMRIPrep docker image could be a helpful template: https://github.com/nipreps/fmriprep/blob/master/Dockerfile

**Comment by oesteban** [comment]
MC, plotting, spatial normalization to MNI, that I can think of quickly

**Comment by effigies** [comment]
I see. What if you do vanilla MC, generate the motion-corrected series and just take the median image? Or is it important to have preprocessing-quality MC?

**Comment by oesteban** [comment]
That would be okay. The only reason why I would think of something a bit more complicated is ensuring synthstrip (which is currently not used, but the plan is to port to it) behaves robustly because the reference has more love in it.

**Comment by oesteban** [comment]
Since synthstrip is not used yet, I think we can have the vanilla option to start with

**Comment by araikes** [comment]
@oesteban, any updates on this? I have a large dataset that would definitely benefit from the DWI QC workflow if it can get up and running.

**Comment by celprov** [comment]
@oesteban we are running into the same issue with running MRIQC on our hcph-pilot data using singularity

**Comment by yibeichan** [comment]
I ran into the same issue with 23.1.0 on HPC via slurm. do we have a solution here? Should I go back to use a lower version?

**Comment by effigies** [comment]
There are basically three possible solutions:

1) Add FreeSurfer to the Docker image (possibly filtering most out) and increase the build time significantly.
2) Upload `mri_robust_template` only to some host and install it in Docker.
3) Select/write a different EPI reference workflow/function.

The first two will also mean needing to handle injecting a FreeSurfer license file when running MRIQC, which we haven't needed to do before and has the potential to annoy users.

In any case, the limiting factor is developer time, so I suspect I speak for @oesteban in saying that help would be appreciated.

I've recently factored out some of an older BOLD reference workflow here: https://github.com/nipreps/fmriprep/blob/next/fmriprep/workflows/bold/reference.py

There's nothing BOLD-specific there, and this should work with diffusion. If someone wants to copy that workflow here (I would suggest into `mriqc/workflows/diffusion/base.py`, just above `hmc_workflow`) and update the docstring to be less BOLD-specific, that would probably be the fastest path forward. You would then be replacing this node:

https://github.com/nipreps/mriqc/blob/f360d1eb46909626c4ca9dbeb5514c3d8fab29e7/mriqc/workflows/diffusion/base.py#L141-L145

And you would need to update any connection involving `dwi_reference_wf` in this connection statement:

https://github.com/nipreps/mriqc/blob/f360d1eb46909626c4ca9dbeb5514c3d8fab29e7/mriqc/workflows/diffusion/base.py#L200-L214

**Comment by effigies** [comment]
Yes, please do!

**Comment by jennan** [comment]
Hello,

I encountered the same issue. As a *temporary* fix, I have built an Apptainer container with MRIQC + Freesurfer (for mri_robust_template) + MRtrix3 (for dwidenoise). It's available on [dockerhub](https://hub.docker.com/r/maximerio/mriqc) and can be pulled using

```
apptainer pull mriqc.sif "oras://docker.io/maximerio/mriqc:v1.0.0"
```

*Note: tag is the version of the github repo where the definition file is, not MRIQC, which is 23.1.0.*

It should work the same with Singularity but I haven't tried it.

Please note the container is quite big :sweat_smile:  (13 Gb).

I used it to run MRIQC with `dwi` and `T1w` modalities and, to my great surprise, did not ask for any Freesurfer license at any point (Freesurfer is installed using the .deb package).

I hope this can be of use to other people :slightly_smiling_face:.
