### ISSUE TITLE
Wrong filename when downloading json file from rating widget [unknown_unspecified.json]

### ISSUE THREAD

**Issue by jaimebarran** [nipreps/mriqc#1127]
### What happened?

I added the plugin 'rating widget' to mri qc report generation. The reports were well built, but when I tried to qualify subjectively the quality of the image with the rating widget, the downloaded file is always with the same filename: `unknown_unspecified.json`.
It would be good that the filename would be as: `dataset_subject.json`.

### What command did you use?

I built the docker image myself, but that worked. The thing that didn't work was the rating widget created along with the report (when downloading the json file).
My command to run the docker was:
```shell
docker run -it --rm -v /home/jaimebarranco/Desktop/samples_v3_bids:/data:ro -v /home/jaimebarranco/Desktop/mreyeqc_output:/out mreyeqc:latest /data /out participant --participant_label 001
```

### What version of the software are you running?

"""Version file, automatically generated by setuptools_scm.""" __version__ = "0.1.dev3288+g5f95281.d20230628"

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Additional information / screenshots

Files to look at:
1. mriqc:
- mriqc/reports/individual.py
- mriqc/data/bootstrap-anat.yml
2. nireports:
- nireports/assembler/report.py
- nireports/assembler/data/rating-widget/bootstrap.yml
- nireports/assembler/data/rating-widget/footer.tpl
- nireports/assembler/data/rating-widget/header.tpl

**Comment by celprov** [comment]
Hi Jaime,
Thanks for this good suggestion.
#1188 will solve the bug regarding the subject name being unspecified.
For the dataset being unknown, adding the --dsname <dataset_name> flag when running MRIQC would solve it.
