### ISSUE TITLE
Running group produces "KeyError: 'dwi'"

### ISSUE THREAD

**Issue by jbwexler** [nipreps/mriqc#1128]
### What happened?

The group reports are still created but it produces the error below. This occurred on two separate datasets.

### What command did you use?

```shell
mriqc /corral-repl/utexas/poldracklab/data/OpenNeuro/raw/ds001555 . group -w /corral-repl/utexas/poldracklab/data/OpenNeuro/mriqc/work/ds001555
```

### What version of the software are you running?

23.1.0

### How are you running this software?

Other

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
> Traceback (most recent call last):
>   File "/work2/03201/jbwexler/frontera/anaconda3/envs/mriqc/bin/mriqc", line 8, in <module>
>     sys.exit(main())
>   File "/work2/03201/jbwexler/frontera/anaconda3/envs/mriqc/lib/python3.10/site-packages/mriqc/cli/run.py", line 206, in main
>     dataframe, out_tsv = generate_tsv(output_dir, mod)
>   File "/work2/03201/jbwexler/frontera/anaconda3/envs/mriqc/lib/python3.10/site-packages/mriqc/utils/misc.py", line 181, in generate_tsv
>     jsonfiles = list(output_dir.glob("sub-*/**/%s/sub-*_%s.json" % (IMTYPES[mod], mod)))
> KeyError: 'dwi'
```

**Comment by araikes** [comment]
Probably related to #1125

**Comment by askieslinger** [comment]
I am also running into this error and I don't even have any dwi data.

**Comment by oesteban** [comment]
Was this not fixed by #1148?

**Comment by celprov** [comment]
@oesteban yes I think so.

**Comment by abfeld007** [comment]
Hi I am running MRI v23.1.0, but I still got the 'dwi' error when I am not using any DWI files (and my dataset passed the bids validator). 
----------------------

Traceback (most recent call last):
  File "/opt/homebrew/bin/mriqc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mriqc/cli/run.py", line 206, in main
    dataframe, out_tsv = generate_tsv(output_dir, mod)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mriqc/utils/misc.py", line 181, in generate_tsv
    jsonfiles = list(output_dir.glob("sub-*/**/%s/sub-*_%s.json" % (IMTYPES[mod], mod)))
                                                                    ~~~~~~~^^^^^
KeyError: 'dwi'
