### ISSUE TITLE
AnFileNotFoundError: /tmp/work/mriqc_wf/.... error

### ISSUE THREAD

**Issue by mohamadhase** [nipreps/mriqc#1132]
### What happened?

I am trying to run the mriqc on a BIDs data, I got the following error - it seems the mriqc cant find the nii fils however I made sure several times that the files are organised as required. 

FileNotFoundError: /tmp/work/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..data..sub-02..anat..sub-02_T1w.nii.gz/metadata/result_metadata.pklz

Also tried several version of mriqc but it doest work, then its not a version issue.

### What command did you use?

```shell
docker run -it --rm -v /Users/username/ds003826:/data:ro -v /Users/username/ds003826/output:/out nipreps/mriqc:22.0.6 /data /out participant --participant_label sub-02
```

### What version of the software are you running?

latest

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

Anatomical derivatives

### Please copy and paste any relevant log output.

```shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 451, in _async_callback
    result = args.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
FileNotFoundError: /tmp/work/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..data..sub-02..anat..sub-02_T1w.nii.gz/metadata/result_metadata.pklz
```

**Comment by oesteban** [comment]
Unfortunately, we didn't have the bandwidth to take care of this and after over a year, I believe this may be closed. @mohamadhase please reopen if the issue remains or open new issues if you hit some different problem. Thanks for posting.
