### ISSUE TITLE
[Report] Move background visualization of anatomical images up above the zoomed-in view of the brain

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#1150]
### What would you like to see added in this software?

After many years evaluating T1w and T2w image quality with MRIQC, I often find myself jumping directly to the background visualization before anything else.

I'm now sure that the background should be looked at at the beginning of the assessment to maximize efficiency. Otherwise, you keep jumping back to the zoomed-in mosaic to see if defects are visible within the brain.

### Do you have any interest in helping implement the feature?

Yes

**Comment by celprov** [comment]
I like it! I think we should do the same for the functional report, that is move the standard-deviation before the average BOLD.
