### ISSUE TITLE
Feature request: automatically delete all intermediate files after successfully creating the individual reports

### ISSUE THREAD

**Issue by shinneuro** [nipreps/mriqc#1168]
### What would you like to see added in this software?

Hi,

I am using `mriqc` version 23.1.0, and it seems like the images are no longer embedded in individual html reports, after `mriqc` starts to utilize `nireports` for generating html reports.

However, when it comes to easy sharing and maintenance, I think a single html is better.
It would be nice if we could select between self-containing or the current approach.

Also, it would be a great addition, to automatically delete all intermediate files after successfully creating the individual reports. Right now, it is a bit tedious to manually delete the huge intermediate files in `mriqc_wf` folder (in my case, it is more than 800gb....).

Many Thanks,
Minho

### Do you have any interest in helping implement the feature?

No

**Comment by oesteban** [comment]
Hi @shinneuro, I've redirected you question about the reports to *NiReports*. Please follow up there.

I have also modified the title of the issue to reflect the second proposal.

**Comment by oesteban** [comment]
Upon further consideration, I don't think we can easily have a meaningful implementation of this anytime soon. Ideally, this should be handled by nipype, which could wipe out the intermediate folders on the go, once no more computational nodes depend on those results anymore.

If implemented just as an rmtree at the end of MRIQC, I think that is not very different from manually removing them after the full process finishes. Doing this "smartly" enough not to delete other processes folders is complicated, while it should be fairly easy for a user to point processes at different locations (even temporary) instead.

We will not address this immediately.

**Comment by shinneuro** [comment]
Hi, @oesteban, 

I understand and support your rationale.
Anyway, thank you for careful consideration of my request :)
