### ISSUE TITLE
dwi key is not defined for group report generation

### ISSUE THREAD

**Issue by celprov** [nipreps/mriqc#1173]
### What happened?

The dwi key is not defined in the QCGROUPS dictionary in `mriqc/reports/groups.py` l.46

### What command did you use?

```shell
mriqc /data/datasets/hcph /data/derivatives/hcph-derivatives/mriqc_23.2.0/ --verbose-report group -vv
```

### What version of the software are you running?

23.2.0

### How are you running this software?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Traceback (most recent call last):
  File "/home/cprovins/.local/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/home/cprovins/code/mriqc/mriqc/cli/run.py", line 217, in main
    group_html(
  File "/home/cprovins/code/mriqc/mriqc/reports/group.py", line 238, in gen_html
    for group, units in QCGROUPS[mod]:
KeyError: 'dwi'
```

**Comment by WilliamFCB** [comment]
@celprov 
I got the same error with version 23.1.0 (thought this was the latest version). However, 23.0.1 seems to work fine.

**Comment by boifat** [comment]
I literally had the same issue. I am using dcm2bids to convert all my data into BIDS format. All my datasets are T1w. I ran the MRIQC on participant level without problem, but when I try to do group I ran into the same error of :"dwi"
