### ISSUE TITLE
Input deface mask for unbiased results.

### ISSUE THREAD

**Issue by bpinsard** [nipreps/mriqc#1182]
### What would you like to see added in this software?

I cannot find anywhere in the docs/code/issues mention of input of deface mask, from command line or BIDS.
For instance, if one want to share mriqc results and first defaces the raw BIDS images, running mriqc afterward will estimate some metrics in zeroed (or blurred depending on the defacing tool) portion of the images, biasing the IQM that compute background noise and such.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by celprov** [comment]
Hi Basile,
I recently noted that some IQMs are consistently zero over a range of datasets including one dataset with defaced and nondefaced images and a range of MRIQC versions.
As far as my investigation goes:
- summary_bg_p05 is ALWAYS zero
- qi_1 is often zero
- very often summary_bg_mad=summary_bg_median=0 and fber= -1

I suspect there is a problem with the way those IQMs are computed. 
I'm wondering whether our observations are related.

**Comment by bpinsard** [comment]
HI Céline,
I have seen such warning raised in mriqc recently, which triggered this more general question as I foresee it to be an issue in our automated pipelines with initial defacing. If some noise measures relies on signal variance in background, any zeroed-out regions with artificially decrease it.

**Comment by psadil** [comment]
FWIW, I've been working with a multi-site dataset where one of the scanners always produces images that have backgrounds that comprise mostly 0s and have been told that this is common for images acquired with SENSE. Here is an example (pink => 0).

![fig_uc-sense](https://github.com/nipreps/mriqc/assets/8172767/7d1751a5-2c38-42b7-a119-61b85220fd4e)

For images from this scanner, we mostly ignore any metric that involves a background intensity but would of course appreciate alternatives.

**Comment by oesteban** [comment]
> ### What would you like to see added in this software?
> 
> I cannot find anywhere in the docs/code/issues mention of input of deface mask, from command line or BIDS. For instance, if one want to share mriqc results and first defaces the raw BIDS images, running mriqc afterward will estimate some metrics in zeroed (or blurred depending on the defacing tool) portion of the images, biasing the IQM that compute background noise and such.
> ### Do you have any interest in helping implement the feature?
> 
> Yes, but I would need guidance
> ### Additional information / screenshots
> 
> _No response_

We are finalizing Celine's registered report on this - https://doi.org/10.17605/OSF.IO/QCKET

We believe this report will basically support the idea that MRIQC reports should be shared WITH faces (i.e., pre-denoising) to allow users run QC in settings as close as possible to having the full dataset. Obviously, if someone reconstructed the original volume (with face) from MRIQC's reports (or managed to identify the person) this would be a big problem, but for now we understand it is not possible.

Regarding the all-zeros problem, I think we should address it separately.

**Comment by oesteban** [comment]
Please reopen if the response is not satisfactory ;)
