### ISSUE TITLE
`timeseries.json` files are unnecessarily duplicated for each processed image

### ISSUE THREAD

**Issue by celprov** [nipreps/mriqc#1183]
For each image that is processed by MRIQC, it generates an associated 'timeseries.json' file.
Yet, that file always contains the same information.

I propose writing a single `timeserie.json` at the root of the derivatives folder to avoid unnecessary file crowding.

**Comment by oesteban** [comment]
c.f. https://github.com/nipreps/mriqc/discussions/1335

**Comment by oesteban** [comment]
Let's address this together with #1184
