### ISSUE TITLE
Do not clean up FA for degenerate tensors within DTI node

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#1215]
### What happened?

We are immediately cleaning up the FA: https://github.com/nipreps/mriqc/blob/61b59e01777fccd381fee9ac4ffc28a7b65c2f5c/mriqc/interfaces/diffusion.py#L472-L473 and that precludes that we calculate the percentage of degenerate tensors as an IQM or plot them highlighted for visual QA/QC.

Methods that require a "massaged" FA (e.g., to calculate the CC mask) should take these two easy steps on their own.

/cc @arokem @teresamg 

### What command did you use?

```shell
-m dwi
```

### What version of the software are you running?

master

### How are you running this software?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by arokem** [comment]
What's the point of the FA file? Where is it used subsequent to saving?

**Comment by oesteban** [comment]
Generating the reports, mostly.
