### ISSUE TITLE
Potential bug: duplciate `tpms_std2t1w` nodes in spatial_normalization workflow

### ISSUE THREAD

**Issue by tclose** [nipreps/mriqc#1232]
### What happened?

Nothing happened, just something that looks strange in the code.

In the spatial_normalization workflow https://github.com/nipreps/mriqc/blob/c8e74914beaa0a674b6b07b41ae4771713c53e4d/mriqc/workflows/anatomical/base.py#L266-L306

there appears to be a duplicate node named `tpms_std2t1w`. Unless I don't understand the logic, is the second map node meant to be named something different?

### What command did you use?

```shell
N/A
```

### What version of the software are you running?

master (c8e74914beaa0a674b6b07b41ae4771713c53e4d)

### How are you running this software?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
N/A
```

### Additional information / screenshots

N/A

**Comment by oesteban** [comment]
I can confirm this is an error.
