### ISSUE TITLE
Type annotation of config module

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#1248]
In general, it would be best practice to annotate, but it is of particular interest to the config module, as it will make the documentation of settings way more transparent and clear.

Any takers? 

cc/ @celprov @mckenziephagen @teresamg @ZviBaratz

**Comment by celprov** [comment]
I'm afraid I don't understand what is needed.

**Comment by oesteban** [comment]
Here's a gentle explanation about type annotation: https://blog.logrocket.com/understanding-type-annotation-python/.

In practice, this is about adding type hints to each of the configurable variables. For example, instead of:
```Python
x = 5.0
```
you can annotate this and say:
```Python
x: float = 5.0
```
which explicitly says this variable should be a float.

Type annotation also works for functions:

```Python
def hello(name):
    print(f'Hi {name}')
```
becomes:
```Python
def hello(name : str) -> None:
    print(f'Hi {name}')
```

which explicitly tells you the function accepts a string through the argument `name` and returns a `None`.

**Comment by ZviBaratz** [comment]
If it's not too urgent, I wouldn't mind trying to take it on sometime in the next couple of weeks.

**Comment by oesteban** [comment]
@ZviBaratz - two weeks is excellent timing.

**Comment by oesteban** [comment]
Done in #1288.
