### ISSUE TITLE
Add a pre-commit configuration file

### ISSUE THREAD

**Issue by zvi-quantivly** [nipreps/mriqc#1267]
### What would you like to see added in this software?

Enable developers to `pre-commit install` and facilitate compliance with the codebase's standards.

### Do you have any interest in helping implement the feature?

Yes

**Comment by oesteban** [comment]
As I have mentioned elsewhere, I'd rather go without pre-commit until that project's leadership changes or if an alternative is proposed instead of pre-commit for the same purpose.

**Comment by zvi-quantivly** [comment]
OK. In that case, I'll make a PR to remove it from the dev requirements.
