### ISSUE TITLE
Option to skip measurement calculation

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqc#209]
Sometimes it might be useful to only generate reports and skip the time consuming measurement calculations.

**Comment by oesteban** [comment]
Something like ```mriqc bidsdir/ out/ group``` ?

**Comment by chrisfilo** [comment]
more like
`mriqc bidsdir/ out/ participant --reports-only`

This way we can still run it efficiently in parallel (if needs be). Group level would not be necessary in such case since reports could be generated for each subject independently.

**Comment by oesteban** [comment]
I've been looking into this, and right now the report generation is a nipype node. This could be possible if could cut off the graph all the previous nodes to the report generation. This way, only the report generation and the subsequent datasink would be run.

But I feel that this is a bit of overkilling a problem that nipype already solves, right?

**Comment by oesteban** [comment]
``--reports-only`` has existed for a long while now, this was reopened by mistake.
