### ISSUE TITLE
Add input hook for general nipype setting config

### ISSUE THREAD

**Issue by jvarada** [nipreps/mriqc#300]
It looks like right now the only nipype setting that can be specified by a config file is the task runner plugin. It would be nice if you could just load a general nipype config file in order to allow configuration of other nipype run parameters too, e.g. 'poll_sleep_duration'.

**Comment by oesteban** [comment]
We could have an argument for a nipype config file, and pass it along. That would deprecate the plugin argument. Would that fix this problem?

**Comment by jvarada** [comment]
Yes.

**Comment by oesteban** [comment]
This can be easily done via a `nipype.cfg` file stored in the same folder we are invoking mriqc. If this solution is not acceptable, please reopen.

**Comment by oesteban** [comment]
Closing again because I accidentally reopened.
