### ISSUE TITLE
[idea] Plot mean normalized image intensity?

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqc#320]
http://spinthatresonates.blogspot.com/2016/12/first-few-images-are-brighter-than-rest.html

**Comment by oesteban** [comment]
MRIQC is to identify those nonsteady states and we have some metrics (and the carpetplot) to inform about that. We have initiated some related lines looking at signal drifts and coil failures. I think this suggestion can be closed for now (opened a discussion https://github.com/nipreps/mriqc/discussions/1341).
