### ISSUE TITLE
Calc failing if start_idx is given as a setting

### ISSUE THREAD

**Issue by jvarada** [nipreps/mriqc#321]
```
161207-21:12:54,768 workflow INFO:
	 Traceback (most recent call last):
  File "/src/nipype/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/src/nipype/nipype/pipeline/engine/nodes.py", line 367, in run
    self._run_interface()
  File "/src/nipype/nipype/pipeline/engine/nodes.py", line 477, in _run_interface
    self._result = self._run_command(execute)
  File "/src/nipype/nipype/pipeline/engine/nodes.py", line 597, in _run_command
    cmd = self._interface.cmdline
  File "/src/nipype/nipype/interfaces/base.py", line 1677, in cmdline
    self._check_mandatory_inputs()
  File "/src/nipype/nipype/interfaces/base.py", line 978, in _check_mandatory_inputs
    self._check_requires(spec, name, getattr(self.inputs, name))
  File "/src/nipype/nipype/interfaces/base.py", line 948, in _check_requires
    raise ValueError(msg)
ValueError: Calc requires a value for input 'start_idx' because one of stop_idx is set. For a list of required inputs, see Calc.help()
```

Settings were:
`{'work_dir': '/data/mriqc_test/work', 'report_dir': '/data/mriqc_test/out/reports', 'hmc_afni': True, 'n_procs': 1, 'verbose_reports': False, 'testing': False, 'ants_nthreads': 6, 'write_graph': True, 'deoblique': True, 'output_dir': '/data/mriqc_test/out', 'correct_slice_timing': True, 'bids_dir': '/data/mriqc_test/bids_data', 'start_idx': 5, 'despike': True}`

**Comment by oesteban** [comment]
Thanks for raising this issue. We really need to fix that. This interacts with the automatic detection of non-steady states that @chrisfilo wrote.

Let's define the expected behavior and priority (manually set start_idx shadows the automatic calculation of non-steady states).

Then, we need to identify all the points where this setting is applied. I think right now we may stand close to the Pareto law, with around 80% of the cases covered. This error falls in the other 20% :P

**Comment by chrisfilo** [comment]
@jvarada have you tried not setting the 'start_idx' and seeing if the automatic steady state detector works well enough?

**Comment by jvarada** [comment]
@chrisfilo Is the `exclude_index` param the starting index value from that point onwards after discarding the non-steady state slices? If so, the value I got for the scans I looked at seems about right from what I know for these scans/scanners.

**Comment by jvarada** [comment]
@oesteban When I wired in the start_idx functionality I only wired it to the AFNI HMC pathway. Do you want me to take care of this issue?

**Comment by oesteban** [comment]
If you are brave enough to track it through all graphs generation... that'd be awesome!. But it is a tedious task I've been avoiding for long... :D

**Comment by jvarada** [comment]
@oesteban OK. I'll try to have a PR for this early next week.

**Comment by jvarada** [comment]
@oesteban Is this still running the tests automatically for PRs?

**Comment by oesteban** [comment]
Based on this https://github.com/poldracklab/mriqc/pull/325#issuecomment-282059311, this issue can be closed. @jvarada please reopen if you think this is still broken.

**Comment by oesteban** [comment]
Accidentally reopened when I undid the stale bot issue closure festival.
