### ISSUE TITLE
Do not clip group report scatterplots

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#337]

**Comment by chrisfilo** [comment]
Group reports are still being clipped as reported by @nicholst

**Comment by chrisfilo** [comment]
![image](https://user-images.githubusercontent.com/238759/32669258-b91c7066-c5f4-11e7-8588-e3f2bd6960e9.png)

**Comment by chrisfilo** [comment]
https://twitter.com/SudoNeuroSci/status/969821610671771650

**Comment by oesteban** [comment]
Closing in favor of #975.
