### ISSUE TITLE
Profiling does not seem to be working

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqc#459]
From latest master: https://1661-49015296-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/logs/run_stats.log#

All runtime_memory_gb is either "Unknown" or 0.0. I don't think this ever worked - this is the log from the PR enabling profiling: https://1652-49015296-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/logs/run_stats.log#

**Comment by chrisfilo** [comment]
The reason why profiling does not work is because the 'profile_runtime' execution config option is not set to true. This config option is only respected if it is set in a config file - not programmatically.

**Comment by oesteban** [comment]
I'll check on this soon and reopen if it is still not working.
