### ISSUE TITLE
ICA component images do not load in functional report

### ISSUE THREAD

**Issue by danlurie** [nipreps/mriqc#477]
MRIQC v. 0.9.2 (not running via Docker/Singularity, unfortunately).

Running with `--ica` produces a `melodic_reportlet.svg` image in the working directory...  

![screenshot_5_2_17__20_50](https://cloud.githubusercontent.com/assets/1873103/25647681/03b431c6-2f79-11e7-813c-4e5954bea441.jpg)

...but the ICA plots don't load at all in the report page.

![mriqc__individual_bold_report](https://cloud.githubusercontent.com/assets/1873103/25647608/353e6186-2f78-11e7-8fe6-cafd9c7ed11a.jpg)

Here's the command-line call used for this run.

```
mriqc \
    --participant_label $SUB_ID \
    -m T1w bold \
    --n_procs 5 \
    --mem_gb 8 \
    --ica \
    --ants-nthreads 3\
    -w /home/despoB/dlurie/Projects/despolab_lesion/qc/work \
    --report-dir /home/despoB/dlurie/Projects/despolab_lesion/qc/report \
    --verbose-reports \
    /home/despoB/lesion/data/original/bids/ \
    /home/despoB/dlurie/Projects/despolab_lesion/qc/out \
    participant 
```
I've attached the HTML report page as a `.zip`. Let me know if there is any other info I can provide to help track down the cause.

[sub-193_task-rest_acq-64px_run-02_bold.html.zip](https://github.com/poldracklab/mriqc/files/972418/sub-193_task-rest_acq-64px_run-02_bold.html.zip)

**Comment by chrisfilo** [comment]
That is bizzare. Was this run outside without a container? Do you have SVGO
and CWEBP installed (they should be optional)?

**Comment by danlurie** [comment]
Run on a manual install. `svgo` and `cwebp` were not installed when I first encountered the issue, so I just installed them and then re-generated the reports, but the issue persists. 

(Still working on getting Singularity running on our server.)

**Comment by danlurie** [comment]
Update: It seems like the ICA images are there, but something goes wrong when the browser tries to display them. If I scroll down to the ICA section of the report and refresh the page, the component images and plots appear very briefly (<500ms) when the page loads, and then disappear. It's hard to be sure, but during their brief appearance, it looks like the component images much larger than they should be (~5x larger). The plots look like they're the right size. 

Not sure if this helps at all, and I haven't yet had a chance to try running the latest version of `mriqc` or running in a container, but I figured I'd report back just in case.

**Comment by stjep** [comment]
I have the same issue with the ICA output when running the current version of `mriqc` inside a container.

![screenshot 2017-07-27 12 52 42](https://user-images.githubusercontent.com/3305421/28683138-73731b98-72cd-11e7-8359-93707dcc195b.png)

**Comment by stjep** [comment]
The ICA plots seem to render fine for me only if I open the individual reports in Chrome on Windows and Ubuntu. They don't show running Chrome on Mac OS or in Firefox on any OS.

**Comment by chrisfilo** [comment]
That's useful info. We might need to consider a different codec for raster
file compression.

Which version of chrome does it fail on Mac?

On Aug 23, 2017 11:10 AM, "Dan Stjepanović" <notifications@github.com>
wrote:

The ICA plots seem to render fine for me only if I open the individual
reports in Chrome on Windows and Ubuntu. They don't show running Chrome on
Mac OS or in Firefox on any OS.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/mriqc/issues/477#issuecomment-324417597>,
or mute the thread

**Comment by stjep** [comment]
I just tried Mac OS again and it works fine on this version of Chrome, but no other browser. Same deal on Windows, the most recent version of Chrome is fine but IE and Firefox don't work.

Might be that Chrome works always but other rendering engines trip up with the ICA output.

**Comment by chrisfilo** [comment]
Yes - this makes sense considering we use WEBP.

**Comment by oesteban** [comment]
We're not running ICA since FSL was removed, this should affect fMRIPrep only. I'm closing and transferring to NiReports.
