### ISSUE TITLE
duecredit library not included in requirements.txt or setup file instructions

### ISSUE THREAD

**Issue by jvarada** [nipreps/mriqc#549]
Program calls for duecredit pip package, does not install by default when installing mriqc via pipy.

**Comment by oesteban** [comment]
`pip install mriqc[duecredit]` should install that (comes from https://github.com/poldracklab/mriqc/blob/master/mriqc/__about__.py#L84-L90)

Please let me know if that installed duecredit.

If you want to install all the extra dependencies: `pip install mriqc[all]`
