### ISSUE TITLE
Feature Request: Add node that just outputs the name of the current scan being processed

### ISSUE THREAD

**Issue by jvarada** [nipreps/mriqc#603]
A node that just outputs the name of the scan that is being processed through the workflow would be useful for parsing the logs. Right now when there is a failure it looks something like this:

```
2017-07-26 21:51:12,469 workflow:ERROR ['Node BigPlot.a0 failed to run on host cn0678.']
```

To figure out what particular scan was running on the `a0` branch of the workflow, right now I have to parse back the log and pull out the original scan name from one of the known commands another node is running, or reconstructing it from the directory tree, which is cumbersome and error prone.

**Comment by oesteban** [comment]
You are totally right. I've been considering several ways to implement this. This feature request would lay in a blurry line between MRIQC and nipype:

- If we consider it an MRIQC's responsibility, everytime we capture an error we would need to add the forensics to find out the scan of origin.
- Conversely, if nipype implemented BIDS features, nodes and workflows would have the ability of keeping BIDS info (and thus print it when errors happen).

Another option I've thought of is splitting logs per runs. Right now, MRIQC granularity is implemented by scans, so each would have a log (alongside one report and one JSON file).

WDTY?

**Comment by oesteban** [comment]
There's no easy way to implement this in nipype. Perhaps with Pydra this will be possible one day. Closing for being an ancient issue.
