### ISSUE TITLE
AFNI's 3dFWHMx

### ISSUE THREAD

**Issue by kaihwang** [nipreps/mriqc#615]
An update of AFNI's 3dFWHMx on 7.20.2017 changed its default output format:

"20 Jul 2017, RW Cox, 3dFWHMx, level 3 (MAJOR), type 2 (NEW_OPT)
    Require -ShowMeClassicFWHM to get the Forman FWHM estimates

    Otherwise, these results are shown only as zeros.  The intention is to
    make it harder to use an archaic model for the noise spatial
    correlation.  But not to break afni_proc.py, which expects 4 values to
    be output there."

or see:
https://github.com/afni/afni/commit/5b86a6ccf243b36e1475f2be43bede714a3eb81f

This update is causing smoothness calculations to fail:
"traits.trait_errors.TraitError: The 'fwhm' trait of a FWHMxOutputSpec instance must be a tuple of the form: (a float, a float, a float) or a tuple of the form: (a float, a float, a float, a float), but a value of (array([ 0.,  0.,  0.,  0.]), array([  0.478022,   2.26733 ,  13.9357  ,   7.85938 ])) <class 'tuple'> was specified.
Interface FWHMx failed to run. "

**Comment by oesteban** [comment]
Addressed by #669.
