### ISSUE TITLE
zero-filled frame detector false alarm?

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqc#637]
dataset: https://openneuro.org/datasets/ds001037/versions/00001
report: https://s3.amazonaws.com/openneuro.outputs/1361b7bb7d60eddbf8c9595bc6f9ef6f/5dd8e547-44ca-47df-94b0-479b6ea7eeaa/reports/sub-CG_T1w.html

Don't see evidence of rotatation or zero filled frame
![image](https://user-images.githubusercontent.com/238759/29753451-b79979e0-8b26-11e7-9663-85a01c583a39.png)

**Comment by oesteban** [comment]
I'll check locally on that subject. With ``--verbose-reports`` it should be possible to see what is detected as frame.

**Comment by nicholst** [comment]
Just to +1 this... I too am getting "Detected a zero-filled frame, has the original image been rotated?" but there's no apparent rotation, no blank slices.

**Comment by oesteban** [comment]
Mriqc is probably getting confused by the blank from defacing. Is that
possible?

**Comment by nicholst** [comment]
Don't think so. I'm running this on Nifti data fresh from DICOM conversion. I can send the dataset if you want.

**Comment by oesteban** [comment]
That'd be sweet

**Comment by nicholst** [comment]
Here you go! https://www.dropbox.com/s/z32s2p2t1v3f96x/ForOscar.zip?dl=0
(will finish uploading on my pokey ADSL line in 30 min)

**Comment by vscholz118** [comment]
Another +1 here. I also got the same warning for some data that I recently processed with mriqc. Have you ever found out what was the reason for this warning and what to do about it?

**Comment by JohannesWiesner** [comment]
Same here, the visual report looks fine and I cannot see any evidence for rotation nor blank slices..

**Comment by gurraburra** [comment]
I have the same issue, I am however using defaced T1 images.

**Comment by zhaolu660** [comment]
Same here. It appears repeatedly. Have the MRIQC team has a solution or update on it? Maybe we should simply label files with such error as 'good' in postprocessing?

**Comment by oesteban** [comment]
Duplicate of #1035.

As of 23.1.0 this has been disabled, hoping for a more selective detector to be implemented.
