### ISSUE TITLE
Explore replacing MELODIC with GIFT

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqc#671]
From Vince Calhoun:

> If you are just running ica on data without masking, we have efficient pca strategies to solve the pca part with less memory usage. If the ICA is run in deflationary mode with fastICA, then shouldn’t be too much difference between melodic and gift.  In general I prefer symmetric mode as I find performance is better.
> 
> The newer algorithms (like EBM) move beyond the assumption of a fixed unimodal distribution for the sources (which is what informax & fastICA (i.e. melodic uses)), so should do better if your data has more complex sources.  These are a little bit slower though, however will use the memory efficient PCA I mentioned above.

Latest release of GIFT includes nipype interfaces.

**Comment by chrisfilo** [comment]
The most problematic aspect of MELODIC is large memory consumption.

**Comment by chrisfilo** [comment]
Here are the steps that will be required to replace MELODIC with GIFT:

1. Implement nipype GIFT Interface that produces HTML visualization (reportlets). See https://github.com/poldracklab/niworkflows/issues/219
1. Add GIFT installation to [Dockerfile](https://github.com/poldracklab/mriqc/blob/master/Dockerfile).
1. Replace MELODICRPT with GIFTRPT at https://github.com/poldracklab/mriqc/blob/61b7a32c057b7963c8f9ee22f1bb90e818c861d8/mriqc/workflows/functional.py#L164
1. (optionally) Adjust the value of `mem_gb` argument to specify (hopefully) lower memory requirements of GIFT.

**Comment by oesteban** [comment]
Closed in favor of [#1329 (discussion)](https://github.com/nipreps/mriqc/discussions/1329)
