### ISSUE TITLE
Unusual DVARS, outlier count, carpet plot patterns in initial volumes 

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqc#701]
Example 1
![image](https://user-images.githubusercontent.com/238759/37139341-63a70c48-2262-11e8-8242-51dfa44f8cc4.png)

Example 2
![image](https://user-images.githubusercontent.com/238759/37139355-71bd0be8-2262-11e8-8d2b-c4efa429408d.png)

We are seeing this across scanners and sequences. I wonder if this has something to do with the fact that  those values are calculated after motion correction and motion correction is using a reference volume calculated using an average of a subset of X first volumes. https://github.com/poldracklab/mriqc/blob/ca6b21c84566f6aadeb1aac2809d4ec09278b5e3/mriqc/workflows/functional.py#L585

**Comment by chrisfilo** [comment]
Here's a good case we can try to test this theory on: https://s3.amazonaws.com/openneuro.outputs/447d26e4f9fe6ce7b5ff851356280f6a/dae3c6ba-9b1f-471e-b54d-64c9cfc34f91/reports/sub-9_task-cueexposure_bold.html

From https://openneuro.org/datasets/ds001247/versions/00001?app=MRIQC&version=65&job=5a99767bdf832f000104dd30

**Comment by oesteban** [comment]
This issue has gone stale.

For completeness, I'll mention that the outliers records are independent of the head motion estimation.

On top of that, I think this issue could derive further investigation in fMRIPrep, however MRIQC is only intended to open windows into the unprocessed data. Therefore, I lean toward focusing our very limited resources into other more active lines of work.

Please reopen if you disagree with this assessment -- I might be not seeing something relevant here :)
