### ISSUE TITLE
mriqc crashes with --fft-spikes-detector option

### ISSUE THREAD

**Issue by pvelasco** [nipreps/mriqc#754]
Hi,
When I run mriqc on a participant, it crashes when generating the report for the functional runs.  I get that result with both 0.14.2 and the current master.

I'm attaching a sample crash report (for a run with release 0.14.2).
[crash-20180926-183041-UID4265-GenerateReport.a2-9537c75a-c010-4949-a807-089ac7cd6ccf.txt](https://github.com/poldracklab/mriqc/files/2429439/crash-20180926-183041-UID4265-GenerateReport.a2-9537c75a-c010-4949-a807-089ac7cd6ccf.txt)

I'll be submitting a fix shortly.

**Comment by oesteban** [comment]
This was addressed with #755. I reopened it by mistake.
