### ISSUE TITLE
MRIQC stops when submitted as job

### ISSUE THREAD

**Issue by EhsanTadayon** [nipreps/mriqc#763]
Hi, 

When I submit mriqc as a job using sbatch ( memory=32000, ncpus=8), It runs up to "workflow_enumerator.anatMRIQCT1w.ComputeIQMs.ComputeQI2" but it stops and does not proceed anymore ( while the job is still running). If I dont run it as a job (on the server itself), it runs smoothly. 

Any thought why it is the case? I would appreciate it.
thanks

**Comment by oesteban** [comment]
Sorry for the late response. Could you post the submission script with all the arguments?
