### ISSUE TITLE
Flag to output .pklz crash files

### ISSUE THREAD

**Issue by Shotgunosine** [nipreps/mriqc#772]
When debugging MRIQC sometimes it would be helpful to be able to reinstatiate the objects and interact with them via the nipypecli. It'd be great if there was a flag in MRIQC that would change the crashfile output format to pklz. @oesteban pointed out that this is the line where that option is set:

https://github.com/poldracklab/mriqc/blob/b3a581627ef4c58f7e418fb184157aba19c85c09/mriqc/bin/mriqc_run.py#L371

**Comment by Shotgunosine** [comment]
Yay, thanks for taking a look at this again!

**Comment by oesteban** [comment]
This should be easier after #834 is implemented.
