### ISSUE TITLE
BET and FSLMATH error

### ISSUE THREAD

**Issue by MaikusaNorihide** [nipreps/mriqc#780]
Dear experts,
I  manually install MRI QC and FSL, ANTs and AFNI.
but workflow was aborted at bet and fslmath.
```
RuntimeError: Command:
bet /home/maikusa/BIDS_test/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..home..maikusa..BIDS_test..Bids_kakushin..sub-K1703291200..anat..sub-K1703291200_T1w.nii.gz/inu_n4/sub-K1703291200_T1w_conformed_corrected.nii.gz /home/maikusa/BIDS_test/work/workflow_enumerator/anatMRIQCT1w/HeadMaskWorkflow/_in_file_..home..maikusa..BIDS_test..Bids_kakushin..sub-K1703291200..anat..sub-K1703291200_T1w.nii.gz/fsl_bet/sub-K1703291200_T1w_conformed_corrected_brain.nii.gz -A
Standard output:

Standard error:
Image Exception : #63 :: No image files match: /home/maikusa/BIDS_test/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..home..maikusa..BIDS_test..Bids_kakushin..sub-K1703291200..anat..sub-K1703291200_T1w/inu_n4/sub-K1703291200_T1w_conformed_corrected
Image Exception : #22 :: Failed to read volume /home/maikusa/BIDS_test/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..home..maikusa..BIDS_test..Bids_kakushin..sub-K1703291200..anat..sub-K1703291200_T1w.nii.gz/inu_n4/sub-K1703291200_T1w_conformed_corrected
Error : No image files match: /home/maikusa/BIDS_test/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..home..maikusa..BIDS_test..Bids_kakushin..sub-K1703291200..anat..sub-K1703291200_T1w/inu_n4/sub-K1703291200_T1w_conformed_corrected
Failed to read volume /home/maikusa/BIDS_test/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..home..maikusa..BIDS_test..Bids_kakushin..sub-K1703291200..anat..sub-K1703291200_T1w.nii.gz/inu_n4/sub-K1703291200_T1w_conformed_corrected
Error : No image files match: /home/maikusa/BIDS_test/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..home..maikusa..BIDS_test..Bids_kakushin..sub-K1703291200..anat..sub-K1703291200_T1w/inu_n4/sub-K1703291200_T1w_conformed_corrected
```
However, when i put command as follows, bet can be performed.
I think temporary dir path is too long for FSL.
can I change temp. dir paht ? 

>bet  sub-K1703291200_T1w_conformed_corrected.nii.gz sub-K1703291200_T1w_conformed_corrected_brain.nii.gz -A

**Comment by hfxcarl** [comment]
I'm having the same exact issues as the poster of the original issue MaikusaNorihide. 

I'm running mriqc-0.15.2, here is my command:
```
BIDS_DIR=$HOME/code/3T_BIDS
QC_DIR=$HOME/code/3T_QC
mriqc ${BIDS_DIR}/ ${QC_DIR}/ participant --no-sub --participant-label CH201803

```

And the crash error:
> ...
> RuntimeError: Command:
> bet /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w.nii.gz/inu_n4/sub-CH201803_T2w_conformed_corrected.nii.gz /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/HeadMaskWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w.nii.gz/fsl_bet/sub-CH201803_T2w_conformed_corrected_brain.nii.gz -A
> Standard output:
> /usr/local/fsl-6.0.3/bin/bet failed during operation
> Standard error:
> Image Exception : #63 :: No image files match: /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w/inu_n4/sub-CH201803_T2w_conformed_corrected
> Image Exception : #22 :: Failed to read volume /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w.nii.gz/inu_n4/sub-CH201803_T2w_conformed_corrected
> Error : No image files match: /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w/inu_n4/sub-CH201803_T2w_conformed_corrected
> Failed to read volume /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w.nii.gz/inu_n4/sub-CH201803_T2w_conformed_corrected
> Error : No image files match: /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w/inu_n4/sub-CH201803_T2w_conformed_corrected
> Image Exception : #63 :: No image files match: /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w/inu_n4/sub-CH201803_T2w_conformed_corrected
> Image Exception : #22 :: Failed to read volume /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w.nii.gz/inu_n4/sub-CH201803_T2w_conformed_corrected
> Error : No image files match: /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w/inu_n4/sub-CH201803_T2w_conformed_corrected
> libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to read volume /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w.nii.gz/inu_n4/sub-CH201803_T2w_conformed_corrected
> Error : No image files match: /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w/inu_n4/sub-CH201803_T2w_conformed_corrected
> /usr/local/fsl-6.0.3/bin/bet: line 401: 83433 Abort trap: 6           ${FSLDIR}/bin/bet2 $IN $OUT -e $bet2opts
> Return code: 1
> 

The input file to the original BET command exists exactly at:
> /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w.nii.gz/inu_n4/sub-CH201803_T2w_conformed_corrected.nii.gz

But the error is saying the file cannot be found at:
> /Users/carl/code/MRIQC/work/mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..Users..carl..code..3T_BIDS..sub-CH201803..anat..sub-CH201803_T2w/inu_n4/sub-CH201803_T2w_conformed_corrected

For some reason the .nii.gz is being dropped from the path name preceeding /inu_n4/...

**Comment by michaelhallquist** [comment]
I have the same problem running mriqc with FSL 6.0.1 on CentOS 6. But as @hfxcarl notes, this runs okay on FSL 5.0.11

**Comment by oesteban** [comment]
Yes, the problem is actually Nipype that is incompatible with FSL 6.

Please downgrade the dependency or use containerized distributions of MRIQC. In the future, the strategy is not to use FSL at all and free MRIQC of its noncommercial limitation.

**Comment by Joseph-elias** [comment]
hello,
Did someone found the solution of this problem?

**Comment by oesteban** [comment]
@Joseph-elias MRIQC dropped FSL long ago - if you want to use MRIQC, please update to a current version.
