### ISSUE TITLE
Feature request - include date in group_bold.tsv

### ISSUE THREAD

**Issue by bkossows** [nipreps/mriqc#793]
Please add "date of scan" in group tsv. Then one could create a time-wise plot to follow a scanner performance.

**Comment by oesteban** [comment]
I believe this could be a great use of MRIQC outputs, but I believe users can easily implement it themselves. Since MRIQC shares the IQMs by default, this would bring privacy issues we don't want to deal with unless a critical mass of users really push for the feature.
