### ISSUE TITLE
use python to run functional image qc

### ISSUE THREAD

**Issue by zzstefan** [nipreps/mriqc#797]
Hi

I don't have the BIDS format fmri data and my data can't be transformed into BIDS format because I don't have the .json files. So how should I do  If I only to want to get a visual report for functional images QC?
 Can I use python to get this? I used the wf=fmri_qc_workflow() function, but I can't find anything in the output_dir.

Thanks.

**Comment by oesteban** [comment]
Please, follow up on #898.
