### ISSUE TITLE
mriqc fails on particular subject

### ISSUE THREAD

**Issue by dkp** [nipreps/mriqc#805]
Dear mriqc experts,

I have two subjects (same scanner protocol, same conversion from Dicom to NIFTI using Heudiconv, same version of Docker, same version of mriqc, same machine). 
1034 was networked to Horos on my machine from the scanner back in early July 2019.
1040 was copied to Horos on my machine from a USB key today Sept 20, 2019.
Otherwise, they were processed the same way. 

I  reran mriqc on 1034 today and mriqc is happy with it. 
However, when I run mriqc on 1040, mriqc crashes (sample log for the anatomical file attached--similar logs are produced for each of the functional files).  I'm running a different Docker BIDS tool now on 1040 and it is apparently processing the anatomical image, without incident.  I have run mriqc dozens of times and never had any problem.  I've tried restarting Docker, updating Docker, reinstalling the mriqc image.  I looked at the NIFTI data and JSON data for 1040...and it *seems* to be fine (the images are viewable, and have the right dimensions, and a similar size to all of the 1034 images).

I'm running out of ideas.  Any insights would be appreciated! 

Thank you for your time (and terrific tool).

-Dianne

[crash-20190920-221549-root-metadata.a0-466c71ae-fae6-4c89-9580-258ad193be2a.txt](https://github.com/poldracklab/mriqc/files/3637940/crash-20190920-221549-root-metadata.a0-466c71ae-fae6-4c89-9580-258ad193be2a.txt)

**Comment by oesteban** [comment]
Hi Dianne, it indeed seems like a corrupted file. Most likely the json sidecar (please check the json is valid itself with an online checker), but the nifti could be the problem too.

**Comment by dkp** [comment]
Aha, thanks for your response! Although the JSON file is valid json and the nifti file is fine, Heudiconv generated the data padding key which seems to have caused the problem: https://neurostars.org/t/valueerror-embedded-null-byte-during-fmriprep-1-0-0-rc10/974/4
Thanks for your response, getting rid of that key in the json does the trick. I have not yet tried the -minmeta flag recommended at the link.

**Comment by oesteban** [comment]
(I accidentally reopened this issue)
