### ISSUE TITLE
Docker definition is outdated and includes known vulnerabilities

### ISSUE THREAD

**Issue by verdurin** [nipreps/mriqc#813]
Hello

I have been testing the Docker image for `mriqc` and ran a scan over it using `clair`.

It finds over three hundred CVEs.
Obviously not all of these will be serious. However, I think it would be prudent to move to a newer base image.

I'm happy to submit the report to you, if that would be helpful.

**Comment by oesteban** [comment]
@verdurin - I just updated the Dockerfile for the upcoming 21.0.0rc0. I would appreciate a second pair of eyes to review it. For the time being, I'll close this one. If you find specific vulnerabilities in the new one, please reopen this issue or maybe start a fresh new one.
