### ISSUE TITLE
MRIQC crashing on resting data only

### ISSUE THREAD

**Issue by evasqin** [nipreps/mriqc#821]
Hi,
We have been running MRIQC on our data and we have recursive problem with resting state data. The crash log shows a problem with null bytes, but we did not use Heudiconv to convert our data and we could not find the padding key in our json file. And this error occurs with resting data only, all other data (T1 and task fMRI) run smoothly on MRIQC.
I have the crash log and an example json attached here. 
Thank you very much!
Eva
[crash-20191211-182511-UID16777218-metadata.a3-792e29f6-a9b5-425d-b258-c6448765e0cf.txt](https://github.com/poldracklab/mriqc/files/3952094/crash-20191211-182511-UID16777218-metadata.a3-792e29f6-a9b5-425d-b258-c6448765e0cf.txt)

[__REST_20191210142255_15.txt](https://github.com/poldracklab/mriqc/files/3952099/__REST_20191210142255_15.txt)

**Comment by oesteban** [comment]
Closing as this is a very old issue and we never had time to have a deeper look. From what I see in the crash file and the metadata it is hard to tell what could be happening.
