### ISSUE TITLE
MRIQC does not run behind "Analysis levels: participant" after starting container

### ISSUE THREAD

**Issue by wulms** [nipreps/mriqc#825]
Hey dear Poldracklab-Team,
I encountered a strange issue. Maybe it is, because I am new to docker and using it only for about a week.

I got MRIQC in Docker to run, when I have a folder containing only two subjects from the BIDS compatible dataset (tested with BIDS-validator). I got the reports, output created and -v shows lots of diagnostic output.

But when I tried to apply it to my whole dataset (about 1600 subjects) nothing else happens, than the output shown in the command below. I read about memory issues, when processing lots of subjects, so I also tried it using only selecting using (--participant-label) only one subject from that folder, but also there is nothing else happen like without participant-label? In each case, the log folder is created, but stays empty. It does not went further, than behind this output shown below, but if i use docker stats the processor and ram is in use? I also tested the participant-label with and without "sub-". Or adding a / to the end of my absolute paths. 

The strange thing is, that it works, when there are only the two randomly copied subjects into my home directory on Ubuntu 18.04. 

This is my command:

`docker run -i --rm -v /media/niklas/Vierer/BIDS_clean/base_protocol/sourcedata:/data:ro -v /media/niklas/Vierer/BIDS_clean/base_protocol/mriqc:/out poldracklab/mriqc:latest /data /out participant --participant-label sub-10189`

This the output: 
`2020-01-14 23:46:09,041 mriqc:IMPORTANT 
    Running MRIQC version 0.15.2rc1:
      * BIDS dataset path: /data.
      * Output folder: /out.
      * Analysis levels: participant.
`

It never went further than this output, also when I wait for some hours. Using --verbose it stops at "Checking BIDS dataset..."

EDIT: This is the output today:

`2020-01-15 00:29:12,647 mriqc:INFO Participant level started. Checking BIDS dataset...
2020-01-15 05:43:15,470 mriqc:CRITICAL MRIQC did not find any target image file under the given BIDS folder (/data). Please check that the dataset is BIDS valid at http://bids-standard.github.io/bids-validator/ .
2020-01-15 05:43:15,470 mriqc:WARNING The following BIDS entities were selected as filters: --participant-label sub-10189. Please, check whether their combinations are possible.
`
Maybe there is something going on with the BIDS dataset checking - if I copy the example subject to another folder on that drive it works again. 

Is it maybe possible, that the BIDS dataset checking is only applied to the participant labels and not to the whole dataset?

Keep up your good work, when it works the outputs are awesome and deliver so much information!

Best regards,
Niklas

**Comment by oesteban** [comment]
It seems your dataset is not valid. I do agree MRIQC should exit at that point (that's the bug), though.

Because this is a problem of a very old version, I assume the issue has been fixed. Please try the newest possible version (I'm about to release a new one) and reopen if this is still an issue.
