### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by vahidbme** [nipreps/mriqc#826]
Hello MRIQC community,

I want to install MRIQC via following pip command: 
pip install git+https://github.com/poldracklab/mriqc.git

At the beginning it had a C++ 14 error and after component installation, I face with following error:

Building wheels for collected packages: traits
Building wheel for traits (setup.py) ... error

ERROR: Complete output from command 'c:\********\python37-32\python.exe'
...
...
..
Failed to build traits

**Comment by oesteban** [comment]
Have you tried with a stable release? I.e.,

```
pip install mriqc
```
