### ISSUE TITLE
Get HTTP Error 502 while using mriqc web API

### ISSUE THREAD

**Issue by Vincent-wq** [nipreps/mriqc#828]
Hi, @oesteban @dbirman 
After MRIQC (most recent docker version) finished succesfully on my small dataset, I would like to interprete the results based on the distribution of all the IQMs of my dataset and the shared dataset from mriqc web-api. When I am trying the code below, it is giving the below problems after a while. Can you tell me why this is happening? Thanks.

code:
`# T1
df_t1w = get_iqms('T1w', software=None)
df_t1w_unique = df_t1w.drop_duplicates(subset=['provenance.md5sum'])

# BOLD
df_bold = get_iqms('bold')
df_bold_unique = df_bold.drop_duplicates(subset=['provenance.md5sum'])`

error message:
`HTTPError                                 Traceback (most recent call last)
<ipython-input-9-34db5aa81a92> in <module>
      1 # T1
----> 2 df_t1w = get_iqms('T1w', software=None)
      3 df_t1w_unique = df_t1w.drop_duplicates(subset=['provenance.md5sum'])
      4 
      5 # BOLD

<ipython-input-8-01aec802700a> in get_iqms(modality, versions, software)
     24                 query='where={%s}&page=%d' % (','.join(query), page)
     25             )
---> 26             with urllib.request.urlopen(page_url) as url:
     27                 data = json.loads(url.read().decode())
     28                 dfs.append(json_normalize(data['_items']))

/usr/local/miniconda/lib/python3.7/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

/usr/local/miniconda/lib/python3.7/urllib/request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

/usr/local/miniconda/lib/python3.7/urllib/request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
    640             response = self.parent.error(
--> 641                 'http', request, response, code, msg, hdrs)
    642 
    643         return response

/usr/local/miniconda/lib/python3.7/urllib/request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

/usr/local/miniconda/lib/python3.7/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

/usr/local/miniconda/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 502: Bad Gateway`

**Comment by oesteban** [comment]
Sorry, I'm afraid you attempted to access the database at a moment it was going through some hiccups. Please reopen if this is till an issue.
