### ISSUE TITLE
the input device is not a TTY 

### ISSUE THREAD

**Issue by f4bry** [nipreps/mriqc#845]
Hi,
I am trying to run mriqc using docker on a HPC server. 
Running a single script it works well but when I am trying to run several subjects in parallel, I get the following message:

`the input device is not a TTY `

does it affect the processing?

Some details:
For each subject I am using the following commands in a script "sub-01.sh":

`docker run -it --rm -v 
$bids_dir:/data:ro 
 -v $out_dir:/out poldracklab/mriqc:latest 
  /data /out participant --participant_label sub-01`

and to parallelize I am using GNU Parallel like:
`parallel --verbose bash :::: to_run.sh `

Here to_run.sh includes all the single subjects scripts:

`sub-01.sh 
ub-02.sh
sub-03.sh
....`

Sorry if I am not very clear.
Please let me know if there are better way to run mriqc in parallel.
Thank you!
Fab

**Comment by effigies** [comment]
Thread necromancy, but this is probably more a `parallel` invocation issue.

**Comment by oesteban** [comment]
Please reopen if this is still an issue.
