### ISSUE TITLE
document --nprocs NPROCS and --omp-nthreads

### ISSUE THREAD

**Issue by justbennet** [nipreps/mriqc#849]
The documentation at

https://mriqc.readthedocs.io/en/stable/running.html

shows output from `mriqc -h` that appears to be perhaps not up to date?  It looks like some options are missing that are now available, and maybe shows options that are no longer available?

In particular, it displays

```
             [--upload-strict] [--n_procs N_PROCS] [--mem_gb MEM_GB]
```
but makes no mention of `--omp_nthreads`.  My just-installed mriqc 0.15.2 shows
```
             [--nprocs NPROCS] [--omp-nthreads OMP_NTHREADS] [--mem MEMORY_GB]
```

from `--help`.

I am not an image analyst, just the system administrator, but I need to be able to tell people what the difference is between `--nprocs` and `--omp_nthreads`.

To me, those are very different things, especially in the context of a job on a cluster.  I think those are used by the underlying `nipype`, but very different things could happen if we mix up processes and threads.

In my usual understanding, I might want to have 16 processors, but if how does `nipype` dived up threads to the processor pool if one specifies `--ncpus=16 --omp_nthreads=4`?

I would find it very helpful if a couple of examples of using `--nprocs --omp_nthreads` could be supplied.

I am seeing in `./mriqc/config.py`
```
    nprocs = os.cpu_count()
    """Number of processes (compute tasks) that can be run in parallel (multiprocessing only)."""
    omp_nthreads = os.cpu_count()
    """Number of CPUs a single process can access for multithreaded execution."""
```
which gives me some concern, as on our cluster, jobs do not have whole node assignment, but are launched within a cpuset/cgroup and `os.cpu_count()` returns the the number of physical processors and not the number allocated to the job.

I hope this all makes sense.

**Comment by effigies** [comment]
Definitely worth adding notes on this to the docs. To briefly describe the difference:

1) `--omp-nthreads` sets the maximum number of threads to use for a specific job within the workflow.
2) `--n_procs` sets the maximum number of threads used by all jobs at a time.

So if you have `--n_procs 16 --omp-nthreads 4` you will limit each job to 4 threads and all simultaneous jobs to 16 threads, so you could get up to 16 1-core jobs or 4 4-core jobs (or somewhere in betweeen) running simultaneously.

**Comment by justbennet** [comment]
@effigies I think that the terminology may not be helping here.  I don't believe that `--n_procs` sets the number of 'threads'; it sets the number of processors (or should).  The `--omp-nthreads` should probably correspond to the environment variable `OMP_NUM_THREADS` and be the maximum number of threads that a multi-threaded process can attempt to use.  The `--n_procs` should set the maximum number of processors that can be allocated, and it would be good to know whether the processors on which the processes that NiPype runs its workflow management are included in that and whether that processor is made available to sub-parts of the `fmriprep` workflow.  I think your version of 2. above will cause more confusion because it uses the term 'threads'.  Whether that is correct usage technically or not, it is confusing.

I might suggest (if it is accurate) that those options should mean something like this (I hope I am accurate).  This almost certainly isn't perfect, but I think it may be an improvement.

1. `--omp-nthreads` sets the maximum number of threads that multi-threaded programs used in `fmriprep` can use, e.g., ANTs.  Each thread will be assigned to a processor.

2. `--n_procs` set the maximum number of processors that can be assigned work within an `fmriprep` job, which includes all the processors used by currently running single- and multi-threaded processes.

So if you have --n_procs 16 --omp-nthreads 4 you will limit each job to 4 threads and all simultaneous jobs to 16 threads, so you could get up to 16 1-core jobs or 4 4-core jobs (or somewhere in betweeen) running simultaneously.

This is a confusing topic because the terms process and thread are used to mean different things in different contexts by different people.  I think the ideal would be to accept some technical 'sloppiness' in favor of clarity for the less technical and less experienced.

Thanks for getting back to this!  I hope my suggestion has something worthwhile in it.

**Comment by oesteban** [comment]
> I don't believe that `--n_procs` sets the number of 'threads'; it sets the number of processors (or should).

Both are right. This is what it should be, but, considering how we implemented this in nipype, Chris' definition is valid too for most of the cases.

If you set a higher number of threads than processors, then the nipype heuristic will fall back to the usual understanding of the parameters (e.g., `--n_procs 8 --omp-nthreads 12` will run at most 8 processes in parallel, and each may use 12 threads internally at most).

**Comment by justbennet** [comment]
@oesteban On my cluster, if I request in my job, say, 8 processors, then my job gets assigned to a cgroup that limits my job to using 8 processors of 36.  In my normal work with something like MPI, I would start, say 4 MPI processes, each of which is multithreaded and can run as many threads as are specified by `OMP_NUMTHREADS`, so, in this case 2 each to enable 100% usage of all the processors allocated to my job.

What confuses me is whether `fmriprep` is accounting for things in the same or a different way.  So, if I say `--n_procs 8 --omp-nthreads 12`, then if there were really 8 ANTs processes running, and each of those were using 12 threads, then I would need 96 processors if I want them all to work at 100%.  On the other hand, if I say, `--n_procs 2 --omp-nthreads 4`, then I would think `nipype` would start only 2 main processes, but when (for example), ANTs runs, it can use up to 4 threads each, which quite a lot of ANTs programs can.

The situation I am trying to avoid is when my cluster job has some number of processors, but none of them are able to run at 100%, so the job takes longer because of process swapping.

Does that make sense?  Am I missing something here?

Thanks for looking into this.

**Comment by effigies** [comment]
> If you set a higher number of threads than processors, then the nipype heuristic will fall back to the usual understanding of the parameters (e.g., `--n_procs 8 --omp-nthreads 12` will run at most 8 processes in parallel, and each may use 12 threads internally at most).

I am interpreting this as permitting up to 96 parallel threads, which is not correct based on my reading of the scheduler. If no node is running and the next node requires more resources than are declared available, we run that but nothing else can run until those are freed. So in this case, an ANTs node that uses 12 threads will not run until all running nodes have completed and, once started, will prevent any other node from running.

The [relevant lines](https://github.com/nipy/nipype/blob/570d4649cde374b6df8c67f49cde8276fb894b45/nipype/pipeline/plugins/legacymultiproc.py#L393-L404):

```Python
            next_job_gb = min(self.procs[jobid].mem_gb, self.memory_gb)
            next_job_th = min(self.procs[jobid].n_procs, self.processors)


            # If node does not fit, skip at this moment
            if next_job_th > free_processors or next_job_gb > free_memory_gb:
                logger.debug(
                    "Cannot allocate job %d (%0.2fGB, %d threads).",
                    jobid,
                    next_job_gb,
                    next_job_th,
                )
                continue
```
