### ISSUE TITLE
root permission issues when running mriqc with docker

### ISSUE THREAD

**Issue by geowk** [nipreps/mriqc#854]
Hello,

When running the following command:

docker run -it --rm -v /rawdata:/data:ro -v /results:/out poldracklab/mriqc:latest /data /out participant --participant_label 001 ---omp-nthreads 4

The results output directory existed prior to running the command. It has my username as owner and permissions. However, the subsequent directories and files created by mriqc within the results/ directory have root ownership and permissions. Is there a way to ensure subsequent files created by mriqc maintains the current user  as owner with owner permissions instead of root? There exists a way to do this with fmriprep-docker, but I could not find a similar method for poldracklab/mriqc:latest.

thanks in advance.

g

**Comment by pvelasco** [comment]
Try with the '--user' parameter for 'docker run':

```bash
docker run -it --user $(id -u):$(id -g) --rm -v /rawdata:/data:ro -v /results:/out poldracklab/mriqc:latest /data /out participant --participant_label 001 ---omp-nthreads 4
```
That way the Docker container is run as yourself.
If you want to run it as a different user, you can do:
```bash
username=XXXXX
uID=$(id -u $username):$(id -u $username)
docker run -it --user $uID --rm -v /rawdata:/data:ro -v /results:/out poldracklab/mriqc:latest /data /out participant --participant_label 001 ---omp-nthreads 4
```

**Comment by oesteban** [comment]
Please reopen if the issue persists.
