### ISSUE TITLE
extract BOLD FD data

### ISSUE THREAD

**Issue by dpagliaccio** [nipreps/mriqc#859]
Hello
Is there a way to extract the actual FD & DVARS timeseries data (that is used to create the summary plots)?

**Comment by julfou81** [comment]
Yes, when you look at the nipype intermediary results (you can define when're to save those with  the -w option).
You will be able to find the FD timeserie in _workflow_enumerator⁩/funcMRIQC⁩/fMRI_HMC_afni⁩/⁨_in_file_..work..AudioDisc..sub-01..func..sub-01_task-audiodisc_run-01_bold.nii.gz⁩/ComputeFD⁩/fd_power_2012.txt_

The DVARS timonerie is in _workflow_enumerator⁩/funcMRIQC⁩/ComputeIQMs/⁨_in_file_..work..AudioDisc..sub-01..func..sub-01_task-audiodisc_run-01_bold.nii.gz⁩/ComputeDVARS/sub-01_task-audiodisc_run-01_bold_valid_volreg_dvars.tsv_

**Comment by oesteban** [comment]
Without disregarding what @julfou81 - please do not use the actual FD and DVARS for anything beyond deciding the exclusion of a subject, and more specifically, please do not use them in the analysis as regressors.

If you want to actually do that, the proper piece of software is *fMRIPrep*.
