### ISSUE TITLE
possible error in "Elapsed time" in log files

### ISSUE THREAD

**Issue by jbwexler** [nipreps/mriqc#861]
I ran openneuro dataset ds000172 with mriqc-0.15.1 on 2/15/20 on TACC. There are thirteen subjects, and the longest running subject ran for 4379s, according to the "Elapsed time" at the end of the log files. However, according to TACC's records, this job ran for 14129s. They sent me a few screenshots as evidence, which I've attached (the x-axis in the graph is in hours). Generally when I compare run times given by the log file with TACC's records, they are pretty similar, so this is unusual. One thing to note from the graph screenshot is that the bulk of the computation happened in the last hour of the run.
![Screen Shot 2020-10-01 at 6 00 21 PM](https://user-images.githubusercontent.com/9039426/95388041-99615280-08bf-11eb-9ad5-b53700b9433b.png)
![Screen Shot 2020-10-01 at 6 06 16 PM](https://user-images.githubusercontent.com/9039426/95388048-9bc3ac80-08bf-11eb-8f65-e66a5ec4900d.png)

**Comment by oesteban** [comment]
Probably both pieces of information are true - although they are reporting different issues. The "elapsed time" reported in the log files is basically the subtraction of the timestamp when the logic of the workflow execution if finished and when it is started.

TACC probably retrieved this information from SLURM.

So there seems to be some issue with nipype staging processes of in MRIQC's workflow setup that stalls computers for a very long while. Many people complain that the workflow gets stalled right after it starts - I wonder if those users just didn't have the patience to wait for as long as you did.

Definitely a worrisome bug to chase after.

**Comment by oesteban** [comment]
It seems the "Elapsed time" reporting was dropped from 0.16 on. Since the elapsed time is better estimated by external tools, this issue can be closed.
