### ISSUE TITLE
No attribute 'seg_file'

### ISSUE THREAD

**Issue by hrswearingen** [nipreps/mriqc#867]
Hi - I am trying to use the "bare-metal" MRIQC without docker/singularity, and am running into a workflow node error:

The use of ``template_resolution`` is deprecated
The use of ``template_resolution`` is deprecated
The use of ``template_resolution`` is deprecated
201023-08:25:55,629 nipype.workflow WARNING:
	 Storing result file without outputs
201023-08:25:55,631 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.ComputeIQMs.ComputeQI2" (/Volumes/EXTERNAL/data/ds001_QC/work/mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..Volumes..External..data..ds001..sub-01..anat..sub-01_T1w.nii.gz/ComputeQI2)
201023-08:25:55,958 nipype.workflow ERROR:
	 Node ComputeQI2.a0 failed to run on host Hannahs-MBP.fios-router.home.
201023-08:25:55,958 nipype.workflow ERROR:

I am running on a MacOS version 10.15.7, Python version 3.8.5, and AFNI & FSL are all the most recent versions. 
NiPype version 1.51
ANTs Version: 2.3.4.dev203-g952e7

I am not able to use Docker/Singularity due to security restrictions at my institution. 

I have attached my error log and full output from my command.

I am using sample ds001 data from here: https://drive.google.com/drive/folders/0B2JWN60ZLkgkMGlUY3B4MXZIZW8

[polygonerror.txt](https://github.com/poldracklab/mriqc/files/5429616/polygonerror.txt)
[crash-20201023-091106-hannah-ComputeQI2.a0-5cb8fa9a-0341-4de1-8671-42c1e34aacb4.txt](https://github.com/poldracklab/mriqc/files/5429647/crash-20201023-091106-hannah-ComputeQI2.a0-5cb8fa9a-0341-4de1-8671-42c1e34aacb4.txt)

Any help you can provide would be appreciated. Thank you!

**Comment by hrswearingen** [comment]
Bumping this issue. If I don't use the -m flag, we receive the following error: "AttributeError: '_FMRISummaryInputSpec' object has no attribute 'seg_file'"

I have attached the output of another command.

Thanks.
[mriqc_error.txt](https://github.com/poldracklab/mriqc/files/5440029/mriqc_error.txt)

**Comment by hrswearingen** [comment]
I am bumping this issue again. I am still unable to successfully run MRIQC through the functional pipeline. I am able to run T1w data through the anatomical pipeline with the -m T1w flag, but if I try to run bold data or data without the -m flag I receive the following error message: "AttributeError: '_FMRISummaryInputSpec' object has no attribute 'seg_file'

I am running the bare-metal installation of mriqc and have attached my full command output and the error log.


[error.txt](https://github.com/poldracklab/mriqc/files/5554296/error.txt)
[crash-20201117-095016-sysadmin-BigPlot.a2-a2f6c201-a52c-4585-a3bc-c40978d03b3d.txt](https://github.com/poldracklab/mriqc/files/5554298/crash-20201117-095016-sysadmin-BigPlot.a2-a2f6c201-a52c-4585-a3bc-c40978d03b3d.txt)

**Comment by hrswearingen** [comment]
I have found a solution to this issue.

I have changed line 65 in niworkflows/interfaces/plotting.py, see below. I have not experienced any further errors with mriqc since changing this line, or with fMRIprep.

` #seg_file=self.inputs.in_segm if isdefined(self.inputs.seg_file) else None,
   seg_file=self.inputs.in_segm if isdefined(self.inputs.in_segm) else None, #changed to seg_file to in_segm to get ride of AttributeError`

**Comment by effigies** [comment]
Thanks for digging into this. Running into this in the tests in #862. Problem is we marked the dependencies too broadly, which allowed the API to move on while MRIQC was not active enough to keep up.

I'm going to fix in the short term by pinning to niworkflows 1.1.x. Future effort can update the dependency.

**Comment by oesteban** [comment]
This should have been further addressed in #968.
