### ISSUE TITLE
Request Legend for Carpet Plot

### ISSUE THREAD

**Issue by dkp** [nipreps/mriqc#870]
The original Power 2017 article divided the legend into 8 categories, whereas MRIQC divides the carpet plot into 4 categories. 
The MRIQC color scheme is also different than the original color scheme.
This makes it difficult to divine which colors correspond to which tissue compartments.

I presume blue at the top is grey matter (maybe you've combined cortical, subcortical and cerebellar?).
If you stuck to the original scheme, then green is white matter...but it does not seem large enough to be the white matter.
What are the red and orange categories?

A legend in the report would help a LOT.

**Comment by gaelleroux** [comment]
Hi,

You can find the legend of the carpet plot here: https://fmriprep.org/en/stable/outputs.html?highlight=compcor#confounds-and-carpet-plot-on-the-visual-reports

Best, Gaëlle

**Comment by oesteban** [comment]
I think this would be a good request for @celprov

**Comment by oesteban** [comment]
Done with #968
