### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by costantinoai** [nipreps/mriqc#881]
when I run

`docker run -it --rm -v C:\Users\45027900\Desktop\tmp:/scratch -v D:\Andrea\fov\BIDS:/data:ro -v D:\Andrea\fov\BIDS\derivatives\mriqc:/out poldracklab/mriqc:latest /data /out group`

I get this error:

> Traceback (most recent call last):
>   File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 88, in main
>     dataframe, out_tsv = generate_tsv(output_dir, mod)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/utils/misc.py", line 166, in generate_tsv
>     dfentry = _read_and_save(jsonfile)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/utils/misc.py", line 189, in _read_and_save
>     data = json.loads(Path(in_file).read_text())
>   File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

any idea what is going on? what is the JSON file MRIQC is looking for? 

MRIQC has been run on every participant, and the output folder is populated with participant-level outputs.

**Comment by effigies** [comment]
Your command looks reasonable. Unfortunately, it's going to be a bit cumbersome to debug. I think you should be able to do:

```
docker run -it --rm \
    -v C:\Users\45027900\Desktop\tmp:/scratch \
    -v D:\Andrea\fov\BIDS:/data:ro \
    -v D:\Andrea\fov\BIDS\derivatives\mriqc:/out \
    --entrypoint=python \
    poldracklab/mriqc:latest \
    -m pdb -m mriqc.cli.run \
    /data /out group
```

This will drop you into a PDB shell. Type `c<enter>` to continue until the error. Assuming you see that error, you'll want to type `u<enter>` until you see `data = json.loads(Path(in_file).read_text())`. There you can type `in_file` to see the name of the file, and `Path(in_file).read_text()` to see the text the JSON parser is failing on.

When you're done debugging, you can hit `q<enter>` to leave the debugger.

**Comment by oesteban** [comment]
@costantinoai have you manually edited any of the output JSON files of the participant level?
