### ISSUE TITLE
bug: _tkinter.TclError: couldn't connect to display "localhost:10.0"

### ISSUE THREAD

**Issue by nbeliy** [nipreps/mriqc#891]
When running in tmux (so without X) `mriqc` crashes [(report)](https://github.com/poldracklab/mriqc/files/5865417/crash-20210124-175726-beliy-PlotMosaicNoise.a4-a938d4f7-66f8-43c3-95eb-b3392c6948a7.txt).

Adding in `mriqc/viz/utils.py`:
```
import matplotlib
matplotlib.use("Agg")
```
seems to fix it.

Weirdly, it happens only on one of the tested dataset.

Just in case, my clean [python environmen](https://github.com/poldracklab/mriqc/files/5865484/pip.txt)

**Comment by oesteban** [comment]
I assume this is a bare-metal installation (ie., not a container).

By default, matplotlib uses the tk backend, which requires a display to be present. You can permanently change your system-wide settings by doing the following:

https://github.com/poldracklab/mriqc/blob/b21957f6aa3d1c90841ae32d63b644665c1de098/Dockerfile#L136

Do you think there is something we should do for bare-metal users? Could you contribute a solution?

**Comment by nbeliy** [comment]
Hi Oscar,

indeed I use "bare-metal" installation. I guess the solution that you give should work (with replacing sed by "uncomment", easier to read). This could go to the installation instructions or in FAQ.

From memory you use matplotlib in 3 files, and in one of them you already set backend to Agg. I think it will cost nothing to do the same for other two files.

**Comment by oesteban** [comment]
> This could go to the installation instructions or in FAQ.

Would you be able to send us a fix?

> From memory you use matplotlib in 3 files, and in one of them you already set backend to Agg. I think it will cost nothing to do the same for other two files.

Sure, I think we just need to make sure we set it within a ``supress`` context because it will throw an error if the backend has been set somewhere else.

**Comment by nbeliy** [comment]
I made the pull request. Please check it -- I have no experience with rst.
