### ISSUE TITLE
Are SNR measures for T1w and fMRI suitable for phantom scans?

### ISSUE THREAD

**Issue by tmspvn** [nipreps/mriqc#893]
I would like to compare the SNR of different sequences scanning the same phantom. However, I have noticed the total SNR of the T1w is the average of csf_snr, wm_snr and gm_snr, given the fact a phantom doesn't have structure it looks like SNR for my phantom scans are not correct. Can you confirm?

I also looked at the source code and it looks like the SNR estimation for fMRI data in based on the structural workflow, if so, what kind of input mask the SNR function has? Is it the segmented brain as in the T1w workflow?

**Comment by julfou81** [comment]
You could use snr_total for your phantom. It was done here with MRIQC.

https://f1000research.com/articles/9-1131/v1
