### ISSUE TITLE
Replace FSL dependencies

### ISSUE THREAD

**Issue by ZviBaratz** [nipreps/mriqc#904]
According to #780 it seems FSL 6 isn't supported. If anyone has any insight as to what might be required to integrate it safely, this is the place.

**Comment by oesteban** [comment]
The problem comes from Nipype :(

**Comment by ZviBaratz** [comment]
@oesteban how do you mean exactly? I ran FSL 6 interfaces (relatively) smoothly with Nipype in the past, however it seems the issue I encountered is actually related to nipy/nipype#3211. I might try and fix that sometime soon, I really need to get the QC pipeline going :sweat_smile:

**Comment by oesteban** [comment]
Yes, the first roadblock is nipy/nipype#3211 - but I'm not sure that's not just the tip of the iceberg.

**Comment by oesteban** [comment]
Also, we ideally would like not to depend on FSL because it has commercial restrictions.

**Comment by ZviBaratz** [comment]
I see. Are there any particular alternatives you had in mind for BET and FAST?

**Comment by oesteban** [comment]
For bet, definitely a CNN - (nobrainer?, cc/ @satra). For segmentation too, but I think @NPann already started to test ANTs' Atropos.

**Comment by satra** [comment]
i would suggest kwyk (https://github.com/neuronets/kwyk) which should be helpful for most T1 images to get both brain and segmentation (you may need to combine the classes). give it a try. you would need to run the docker image to run it.

**Comment by ZviBaratz** [comment]
@satra kwyk looks amazing. However, I have to admit I don't have any experience integrating dockerized interfaces into nipype's workflows. Do you have suggestions as to how to approach this?

**Comment by oesteban** [comment]
Let's follow up on kwyk in #933 and the FSL facet on #823.
