### ISSUE TITLE
Change in Normalisation process between MRIQC version 0.14.2 and 0.15.1?

### ISSUE THREAD

**Issue by julfou81** [nipreps/mriqc#908]
Hi, was there a change in the normalisation process for BOLD images between MRIQC version 0.14.2 and 0.15.1? I noticed a difference in the visual report for acquisition with small FOVz, with slices aligned along the Sylvian Fissure.

Output of 0.14.2:

![Capture d’écran 2021-04-15 à 01 16 52](https://user-images.githubusercontent.com/32452352/114792525-d6376600-9d88-11eb-9cf7-e46eb03063f8.png)

Output of 0.15.1:

![Capture d’écran 2021-04-15 à 01 17 13](https://user-images.githubusercontent.com/32452352/114792554-e18a9180-9d88-11eb-8162-1ce570721d96.png)

And a general question: what is the use of the normalisation step for MRIQC in BOLD images? Are there IQMS for bold that are calculated in the template place?

**Comment by oesteban** [comment]
> Hi, was there a change in the normalisation process for BOLD images between MRIQC version 0.14.2 and 0.15.1?

Wow, that is long ago - judging by your findings, yes, there seems to be. However, by looking at your plots it seems 0.15.1 is much better registration than 0.14.2.



> And a general question: what is the use of the normalisation step for MRIQC in BOLD images? Are there IQMS for bold that are calculated in the template place?

I don't think so, but would bet any money on this answer. I'm certain we are bringing some knowledge from the atlas into the bold, particularly to create the carpetplot - other than that there shouldn't be much of a difference, I believe.

**Comment by oesteban** [comment]
Closing due to the lack in activity.
