### ISSUE TITLE
Apply MRIQC on previously skull-stripped 3D-T1w

### ISSUE THREAD

**Issue by RocaVincent** [nipreps/mriqc#909]
Hello

Is it a problem to use MRIQC with previously skull stripped 3D-T1 (volBrain) ? And if it is, what can I do to avoid having biased results ?

**Comment by oesteban** [comment]
> Is it a problem to use MRIQC with previously skull stripped 3D-T1 (volBrain) ?

Yes, MRIQC doesn't work on skull stripped images. Many of the quality metrics will look at portions of the background, which in this case will be all-zeros.

> And if it is, what can I do to avoid having biased results ?

The only thing you could do is redefine "results", and don't use MRIQC in this case.

MRIQC is for raw images (although defaced images are supported for obvious reasons). If the quality assessment you intend to do is on preprocessed data, then you should use some other tool. There are many out there (e.g., https://incf.github.io/niQC/tools).
