### ISSUE TITLE
Error in rpve code

### ISSUE THREAD

**Issue by RocaVincent** [nipreps/mriqc#910]
Hi, I think there is an error in the for computation of rpve quality metric. [Here](https://github.com/poldracklab/mriqc/blob/master/mriqc/qc/anatomical.py#L528), voxels under the lower bound are set to 0, [then](https://github.com/poldracklab/mriqc/blob/master/mriqc/qc/anatomical.py#L531) we have `(1.0 - pvmap[pvmap <= 0.5]).sum()`.  In this statement, all voxels previously set to 0 count for 1 in the sum, and I don't think this is the goal.

**Comment by oesteban** [comment]
Yup, that would be expected. Let me check on the PR and I will provide you with more details on the next steps.
