### ISSUE TITLE
concurrent access to mriqc work dir?

### ISSUE THREAD

**Issue by octomike** [nipreps/mriqc#912]
Is mriqc's work directory supposed to be accessible/usable from two concurrently running mriqc calls?

**If so**: I believe the config file `.mriqc.toml` [must be locked](https://github.com/poldracklab/mriqc/blob/master/mriqc/cli/run.py#L26) while building the workflow. We just had a small headache with this when running many limited mriqc jobs on a cluster in parallel.

**Otherwise**, the documentation could use a small warning with the `--work-dir` argument.

I can try to make a PR in either case if you want me to.

**Comment by oesteban** [comment]
> **Otherwise**, the documentation could use a small warning with the `--work-dir` argument.

I think this would be awesome - care to send the PR?

**Comment by oesteban** [comment]
PR is merged
