### ISSUE TITLE
Missing file for bare-metal installation

### ISSUE THREAD

**Issue by rcwelsh** [nipreps/mriqc#915]
Running on a MacOSX 10.14.6, with pip 21.1.1. Grabbing the requirements file throws an error. I'd like to install the bits to pull out bits to examine the functionality of the code.

Referencing the instructions : https://mriqc.readthedocs.io/en/latest/install.html

`pip install -r https://raw.githubusercontent.com/poldracklab/mriqc/master/requirements.txt`
**ERROR: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/poldracklab/mriqc/master/requirements.txt**

**Comment by oesteban** [comment]
I believe the documentation is out of date - just skipping that `pip install` should do.

**Comment by rcwelsh** [comment]
thanks, i'll give a try later today -- just noticed you reply.

**Comment by oesteban** [comment]
Documentation has been updated. Please reopen if this problem persists.
