### ISSUE TITLE
Checking the entire BIDS directory, even when running a single participant?

### ISSUE THREAD

**Issue by sammosummo** [nipreps/mriqc#922]
I would like to run MRIQC on a large study, one participant per node in parallel on a computing cluster. I'm specifying to perform participant-level analysis as per the documentation.

Based on the fact that the log entry `mriqc:INFO Participant level started. Checking BIDS dataset...` takes a really long time, I'm assuming that MRIQC checks the integrity of the _entire_ BIDS directory for the study, even in single-participant mode? If so, is there some way to skip the BIDS check, or restrict it to just the participant? Otherwise it is quite a large waste of computing time.

**Comment by m-petersen** [comment]
I have the same issue. When running mriqc on a single subject of a 3000 subject bids dataset mriqc requires multiple hours (remaining on a single threaded task for that time) before processing starts.

**Comment by m-petersen** [comment]
Facing the same issue. When running mriqc on a subject of a 2600 subject bids directory pybids takes roughly 10 hours in my case. Is implementing pybids database usage as in fmriprep or qsiprep under consideration?
