### ISSUE TITLE
Add missing data into CONTRIBUTORS table

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#943]
The following contributors have helped MRIQC in one or another way, and we want to give back to them as established by [the *NiPreps* conventions](https://www.nipreps.org/community/CONTRIBUTING/#recognizing-contributions):

* @ZviBaratz -missing ORCID, please confirm all other details.
* @nbeliy - missing ORCID, please confirm all other details.
* @verdurin - missing ORCID and affiliation, please revise name
* @benkay86 - missing ORCID (and only now I realize the affiliation is incorrectly placed under the ORCID column)
* @jdkent - please update your affiliation
* @leej3 - missing ORCID, please confirm all other details.
* @Shotgunosine - please revise affiliation
* @apiccirilli - missing ORCID, please confirm all other details
* @jvarada - missing ORCID, please confirm all other details.
* @pvelasco - missing ORCID, please confirm all other details.
* @justbennet - I could only retrieve your GH handle - Please place your entry in the right position (order is alphabetical by last name and then first name)
* @octomike - I could only retrieve your GH handle and your affiliation - Please place your entry in the right position (order is alphabetical by last name and then first name)

Please let me know if you want to be removed from that table. You can also silence our noise by moving your row to the FORMER.md file. You can always come back to the CONTRIBUTORS.md file whenever you feel you want to.

Fundamental EDIT: the file I'm asking you to PR against is https://github.com/nipreps/mriqc/blob/master/.maint/CONTRIBUTORS.md

**Comment by justbennet** [comment]
@oesteban I submitted a PR with updated information.  Sorry to have needed so much prompting.

**Comment by oesteban** [comment]
This has been addressed. Thank you all!
