### ISSUE TITLE
RuntimeError: Could not fetch template files

### ISSUE THREAD

**Issue by jbwexler** [nipreps/mriqc#959]
I received the following error from MRIQC v21.0.0rc2. I ran it on four datasets and this error only occurred in three subjects spanning two of the datasets:
> (main) login4.frontera(1012)$ cat /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000030-mriqc/.reproman/jobs/local/20211214-102828-29c5/stderr.8
> Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_label-GM_probseg.nii.gz
> 100%|██████████| 7.57M/7.57M [00:00<00:00, 17.1MB/s]
> Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_label-WM_probseg.nii.gz
> 100%|██████████| 6.91M/6.91M [00:00<00:00, 14.7MB/s]
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/workflow.py", line 43, in build_workflow
>     retval["workflow"] = init_mriqc_wf()
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/workflows/core.py", line 50, in init_mriqc_wf
>     workflow.add_nodes([anat_qc_workflow()])
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/workflows/anatomical.py", line 122, in anat_qc_workflow
>     iqmswf = compute_iqms()
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/workflows/anatomical.py", line 318, in compute_iqms
>     for p in get_template(
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 104, in get
>     raise RuntimeError(msg)
> RuntimeError: Could not fetch template files: /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000030-mriqc/code/containers/binds/HOME/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_label-WM_probseg.nii.gz.

The following error also occurred in two subjects spanning one dataset:

> (main) login2.frontera(1062)$ cat /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000201-mriqc/.reproman/jobs/local/20211214-105515-f641/stderr.0
> Traceback (most recent call last):
>   File "/opt/conda/bin/mriqc", line 5, in <module>
>     from mriqc.cli.run import main
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/run.py", line 24, in <module>
>     from mriqc import config, messages
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/config.py", line 108, in <module>
>     from templateflow import __version__ as _tf_ver
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
>     from . import api
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
>     from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 42, in <module>
>     _update_s3(TF_HOME, local=True, overwrite=True)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/_s3.py", line 20, in update
>     retval = _update_skeleton(skel_file, dest, overwrite=overwrite, silent=silent)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/_s3.py", line 55, in _update_skeleton
>     zipref.extractall(str(dest))
>   File "/opt/conda/lib/python3.8/zipfile.py", line 1647, in extractall
>     self._extract_member(zipinfo, path, pwd)
>   File "/opt/conda/lib/python3.8/zipfile.py", line 1697, in _extract_member
>     os.mkdir(targetpath)
> FileExistsError: [Errno 17] File exists: '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000201-mriqc/code/containers/binds/HOME/.cache/templateflow/tpl-Fischer344'

The command I'm using is: 
`code/containers/scripts/singularity_cmd run code/containers/images/bids/bids-mriqc--21.0.0rc2.sing sourcedata/raw /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000201-mriqc participant --participant-label '9001' -w '/scratch1/03201/jbwexler/work_dir/mriqc//ds000201_sub-9001' -vv --nprocs 11 --ants-nthreads 8 --verbose-reports --dsname ds000201 --ica --mem_gb 30`

**Comment by effigies** [comment]
What is the contents of `code/containers/scripts/singularity_cmd`? Seems relevant to what bindings and environment variables are being set.

**Comment by jbwexler** [comment]
Here's that file: https://github.com/ReproNim/containers/blob/master/scripts/singularity_cmd

**Comment by effigies** [comment]
What if we just make https://github.com/templateflow/templateflow another subdataset in `sourcedata/` and set `SINGULARITYENV_TEMPLATEFLOW_HOME=sourcedata/templateflow/`?

**Comment by jbwexler** [comment]
Would we also need to bind that directory or no?

**Comment by effigies** [comment]
Probably not, since the repository root will already be bound.

**Comment by oesteban** [comment]
Any updates on this?

**Comment by jbwexler** [comment]
Yep, we solved this by installing templateflow via datalad (as an ephemeral clone to avoid having to download or copy for each dataset). And then:
SINGULARITYENV_TEMPLATEFLOW_HOME="/path/to/templateflow" SINGULARITYENV_TEMPLATEFLOW_USE_DATALAD="true"
