### ISSUE TITLE
7T / mp2rage data?

### ISSUE THREAD

**Issue by LTomova** [nipreps/mriqc#962]
Hi all,

does MRIQC also work with mp2rage data collected on a 7T scanner?  

Thanks,
Livia

**Comment by effigies** [comment]
Not directly. It would be interesting to try with a T1w image derived from the MP2RAGE sequence, but I would expect some components to work poorly (brain masking and downstream processes have not been optimized for the high background noise levels) and possibly fail altogether. To the extent you do get image quality metrics, they will in many (most?) cases not be comparable with those from the more common 3T T1w sequences.

**Comment by LTomova** [comment]
Thanks for the prompt reply, this is very helpful!
