### ISSUE TITLE
Typeerror in group level analysis

### ISSUE THREAD

**Issue by ulloaa** [nipreps/mriqc#964]
Hello, 

We are getting an error using the group level comand "mriqc mriqc.out.ds001 mriqc.out.ds001 group"

The error (below) occurs only with mriqc 0.15.1 and above. mriqc 0.15.0 works using the command above with no errors.

We are using a singularity container on a linux OS directly converted from the docker container provided. 

Any advice on where this error is coming from and possible workarounds?

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 16, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/parser.py", line 414, in parse_args
    / ("mriqc-%s" % version.split("+")[0])
TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by oesteban** [comment]
First, I would strongly recommend to update MRIQC to the latest stable version.

Second, this looks like the installed environment is sneaking into the image - what is the actual command line you are running?

**Comment by oesteban** [comment]
Please reopen if this is still a problem.
