### ISSUE TITLE
mriqc: error: unrecognized arguments: --hmc-fsl

### ISSUE THREAD

**Issue by JanaHermans** [nipreps/mriqc#966]
Hi, when trying to go through the MRIQC tutorial from https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/MRIQC.html#mriqc-tutorial, I ran into an issue when running the actual script. The error message I got was `mriqc: error: unrecognized arguments: --hmc-fsl`.

**Comment by JanaHermans** [comment]
Script from MRIQC tutorial (https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/MRIQC.html#mriqc-tutorial):

```
#!/bin/bash

#User inputs:
bids_root_dir=$HOME/BIDS_tutorial
subj=01
nthreads=2
mem=10 #gb
container=singularity

#Make mriqc directory and participant directory in derivatives folder
if [ ! -d $bids_root_dir/derivatives/mriqc ]; then
mkdir $bids_root_dir/derivatives/mriqc
fi

if [ ! -d $bids_root_dir/derivatives/mriqc/sub-${subj} ]; then
mkdir $bids_root_dir/derivatives/mriqc/sub-${subj}
fi

#Run MRIQC
echo ""
echo "Running MRIQC on participant $s"
echo ""

if [ $container == singularity ]; then
  unset PYTHONPATH; singularity run $HOME/mriqc_0.15.1.simg \
  $bids_root_dir $bids_root_dir/derivatives/mriqc/sub-${subj} \
  participant \
  --n_proc $nthreads \
  --hmc-fsl \
  --correct-slice-timing \
  --mem_gb $mem \
  --float32 \
  --ants-nthreads $nthreads \
  -w $bids_root_dir/derivatives/mriqc/sub-${subj}
else
  docker run -it --rm -v $bids_root_dir:/data:ro -v $bids_root_dir/derivatives/mriqc/sub-${subj}:/out \
  poldracklab/mriqc:0.15.1 /data /out \
  participant \
  --n_proc $nthreads \
  --hmc-fsl \
  --correct-slice-timing \
  --mem_gb $mem \
  --float32 \
  --ants-nthreads $nthreads \
  -w $bids_root_dir/derivatives/mriqc/sub-${subj}
fi
```

**Comment by oesteban** [comment]
Hi @JanaHermans - I'll look into this, but I can already advance that the action to be taken is actually removing the option. MRIQC is not a preprocessing tool, so how head-motion is calculated should be irrelevant beyond plotting the frame-wise displacement and training models to identify bad data automatically.

**Comment by oesteban** [comment]
Related #904

**Comment by oesteban** [comment]
Okay, just checked and indeed the option got deprecated a while ago, then removed and it does not exist anymore. Please do not use the option. Rationale for the removal is given above.
