### ISSUE TITLE
BET error raised when running via singularity

### ISSUE THREAD

**Issue by ZviBaratz** [nipreps/mriqc#976]
Hi all,

I'm having a strange issue trying to run `mriqc v21.0.0rc2` via singularity. 
When I execute:
```bash
singularity run -B <my_bids_root>:/data:ro,<output_dir>:/out /my_images/mriqc-21.0.0rc2.simg /data/rawdata /out/mriqc participant --no-sub --work-dir /out/work --float32 --participant_label 3
```
I get the following exception:
```bash
...
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
bet sub-3_acq-67388corrected_T1w_conformed_corrected.nii.gz sub-3_acq-67388corrected_T1w_conformed_corrected_brain.nii.gz -A
Standard output:

Standard error:
/opt/fsl-5.0.11/bin/bet: 1: /usr/local/fsl/bin/remove_ext: not found
/opt/fsl-5.0.11/bin/bet: 1: /usr/local/fsl/bin/remove_ext: not found
/opt/fsl-5.0.11/bin/bet: 1: /usr/local/fsl/bin/imtest: not found
/opt/fsl-5.0.11/bin/bet: 154: [: =: unexpected operator
/opt/fsl-5.0.11/bin/bet: 341: /usr/local/fsl/bin/flirt: not found
/opt/fsl-5.0.11/bin/bet: 344: /usr/local/fsl/bin/bet2: not found
/opt/fsl-5.0.11/bin/bet: 347: /usr/local/fsl/bin/betsurf: not found
Return code: 0
```

But when I run:
```bash
docker run -v <my_bids_root>:/data:ro -v <output_dir>:/out nipreps/mriqc:21.0.0rc2 /data/rawdata /out/mriqc participant --no-sub --work-dir /out/work --float32 --participant_label 3
```
It runs smoothly.

Any help resolving this will be greatly appreciated. 
Thank you so much for all your work!

**Comment by oesteban** [comment]
I think your external environment is infecting your singularity container. Have you tried singularity with the ``--cleanenv`` argument?

**Comment by ZviBaratz** [comment]
How embarrassing, I completely forgot about that. Issue resolved :sweat_smile:
However, this might be an indication that it's worth opening a separate issue for adding a dedicated "Running with Singularity" section in the docs to prevent such mistakes in the future, if you approve.

**Comment by oesteban** [comment]
That section should not exist or, at most, just point out to
https://www.nipreps.org/apps/singularity/
