### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Giachi95** [nipreps/mriqc#980]
Hello eveyone,
I'm trying to install mriqc 0.16.1. I've downloaded the .tar.gz installation file, type "_sudo python3 setup.py install_" but an error message occured. This error is the following:

> Running xvfbwrapper-0.2.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-83pv98qf/xvfbwrapper-0.2.9/egg-dist-tmp-zr46naye
> zip_safe flag not set; analyzing archive contents...
> No eggs found in /tmp/easy_install-83pv98qf/xvfbwrapper-0.2.9/egg-dist-tmp-zr46naye (setup script problem?)
> error: The 'xvfbwrapper' distribution was not found and is required by mriqc

I have Python 3.8.10, I already have xvfbwrapper 0.2.9 and numpy 1.20.2!

Please give me some advice.

Thanks,
Giacomo Serra

**Comment by oesteban** [comment]
That mode of installation isn't supported anymore.

Please install with `pip install -e .` from within the project's downloaded folder.
