### ISSUE TITLE
Do not discard confound timeseries and preserve all data?

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqc#992]
This https://github.com/nipreps/mriqc/issues/965#issuecomment-1114570370 has brought up the issue that we are losing a great deal of granularity by reporting only summaries of metrics for BOLD images.

**Comment by psadil** [comment]
I would be interested in this feature and am potentially available to help with an implementation. I'm currently grading scans based on average framewise displacement, proportion of frames with motion above a given threshold, and the maximum motion per frame. MRIQC already makes the first two available, but not the third. Also, without the full timeseries, it can be tricky to explore the impact of different thresholds in the second. So, having the full timeseries would be helpful.

**Comment by oesteban** [comment]
If you take on it, I don't see any reason not to add it to MRIQC :)

@eilidhmacnicol might want to keep an eye on this one too.

**Comment by psadil** [comment]
Great! Happy for the buy-in. Let me know if there is a more formal procedure for specifying a design, but I'm imagining the following decision points.

For values, I'm currently thinking

FD, DVARS, AFNI’s outlier ratio, AFNI’s quality index

Any others to include?

For storage, does a tsv sound okay? Relatedly, for size, I'm inclined to not embed the timeseries in the html report. And for simplicity, I'm also inclined to not upload the values to the webapi. But please let me know if this should be reconsidered. 

I'm guessing that the original summaries would still be stored (in the original json), as a convenience and to not break workflows.
